### PR TITLE
Serde regression tests

### LINKED ISSUE #723: Add regression tests for all serde serializations

### PR DESCRIPTION
**Pull request by tcharding**
Attempts to add regression tests for _all_ types defined in `rust-bitcoin` that implement `Serialize`/`Deserialize`.

- Add a `tests` directory and implement regression tests in there
- Use files for input hex and output bincode to reduce source file clutter
- Copy test block and `include_bytes!` usage from RCasatta's [PR](https://github.com/rust-bitcoin/rust-bitcoin/pull/750)
- Uses Kixunil's macro suggested below
- Adds a single regression test to `util/taproot.rs` for private types

## Note to reviewers
- Uses JSON for opcodes in a separate file (`tests/regression_opcodes.rs`), for all other tests uses bincode.
- Bypasses the order issue for maps by only serializing maps with a single element - is this correct? 

Fixes #723

### CODE REVIEW

**Comment by apoelstra** [comment]
Cool! concept ACK.

File: src/blockdata/opcodes.rs [hunk 1]
```diff
@@ -882,6 +882,15 @@ mod tests {
...
     }
 
+    macro_rules! regression {
+        ($op:ident, $s:expr) => {
+            let op = all::$op;
+            let want = format!("\"{}\"", $s);
+            let got = ::serde_json::to_string(&op).unwrap();
+            assert_eq!(got, want);
+        }
+    }
```
Comment (Kixunil) [inline src/blockdata/opcodes.rs:892]: Something to consider: put each check into a separate function, so that if any of them fails, it'll be quick and obvious to find which one. Since there are many of them, I'd suggest this:

```rust
    macro_rules! regression {
        ($op:ident, $s:expr) => {
            #[test]
            #[allow(non_snake_case)]
            fn $op() {
            let op = all::$op;
            let want = format!("\"{}\"", $s);
            let got = ::serde_json::to_string(&op).unwrap();
            assert_eq!(got, want);
        }
    }
    mod ops {
        regression!(OP_PUSHBYTES_0, "OP_PUSHBYTES_0");
        // ...
    }
```

**Review by Kixunil — COMMENTED** [review]
Concept ACK

File: src/blockdata/opcodes.rs (hunk 1 above)
Comment (tcharding) [reply src/blockdata/opcodes.rs:892]: BOOM! This is nice, thanks.

Comment (RCasatta) [reply src/blockdata/opcodes.rs:893]: Adding the third parameter to `assert_eq!` would achieve a similar result (quickly finding breaks) without adding too many tests?

Comment (Kixunil) [reply src/blockdata/opcodes.rs:893]: There's still benefit of running them independently by seeing all failures. Not sure how important it is.

Comment (tcharding) [reply src/blockdata/opcodes.rs:893]: Since this is regression testing and not really expected to break very often I'm leaning towards @RCasatta's idea, less tests but still able to debug. Open to more opinions however.

Comment (Kixunil) [reply src/blockdata/opcodes.rs:893]: OK, still recommend using a small macro to decrease duplication.

Comment (tcharding) [reply src/blockdata/opcodes.rs:893]: Most definitely, thanks.

**Comment by tcharding** [comment]
There are a few private types in `util/taproot.rs` and I'm not sure if we need to explicitly test them or if the hex used to create a `ControlBlock` is enough. I wrote the following test but Rust 1.29 build fails for some reason (cannot compare an array with a vector) even though all the integration tests are like this?

Do we need this one?
```

    // FIXME: Is this redundant because of serde_regression_taproot_builder() in tests/regression.rs?
    // TaprootMerkleBranch and NodeInfo are private and cannot be explicitly created in regression.rs.
    #[test]
    #[cfg(feature = "serde")]
    fn serde_regression_node_info() {
        use bincode::serialize;

        let s1 = Script::from(vec![0u8, 1u8, 2u8]);
        let s2 = Script::from(vec![3u8, 6u8, 9u8]);
        let ver = LeafVersion::from_consensus(0).unwrap();
        let mut l1 = LeafInfo::new(s1, ver);
        let mut l2 = LeafInfo::new(s2, ver);

        let h1 = sha256::Hash::from_str("cafec44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852babe").unwrap();
        let h2 = sha256::Hash::from_str("deadc44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852beef").unwrap();
        let b1 = TaprootMerkleBranch(vec![h1, h2]);
        let b2 = TaprootMerkleBranch(vec![h2, h1]);
        l1.merkle_branch = b1;
        l2.merkle_branch = b2;


        let info = NodeInfo {
            hash: sha256::Hash::from_str("cafeccafe8fc1c149afbf4c8996fb92427ae41e4649b934ca495991bbabebabe").unwrap(),
            leaves: vec![l1, l2],
        };

        let got = serialize(&info).unwrap();
        let want = [32, 0, 0, 0, 0, 0, 0, 0, 202, 254, 204, 175, 232, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 186, 190, 186, 190, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 202, 254, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228,100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 186, 190, 32, 0, 0, 0, 0, 0, 0, 0, 222, 173, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76,164, 149, 153, 27, 120, 82, 190, 239, 3, 0, 0, 0, 0, 0, 0, 0, 3, 6, 9, 0, 2, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 222, 173, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185,36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 190, 239, 32, 0, 0, 0, 0, 0, 0, 0, 202, 254, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 186, 190];
        assert_eq!(got, want)
    }
```

**Comment by Kixunil** [comment]
Private types shouldn't need serde impls. If they do (because something in the crate uses them inside) then tests are useful to pinpoint the source of problem if something goes wrong.

Change the array to slice to fix compile issue:

```rust
let want = &[32, 0 ...] as &[_];
```

**Review by RCasatta — COMMENTED** [review]
I think we need one of the following:
* move `tests/bincode` and `tests/hex` inside `test_data`
* create `tests/data` and move `test_data`, `tests/bincode` and `tests/hex` inside it

**Comment by tcharding** [comment]
> Private types shouldn't need serde impls. If they do (because something in the crate uses them inside) then tests are useful to pinpoint the source of problem if something goes wrong.

Cool, I think I'll leave this one out. Since we cannot guarantee that the regression tests test _all_ the serde impls I think its probably better to just keep the public API tests, then they are all in one place. Also this test, as its written, won't help pin point any errors that much more than the `ControlBlock` test. Unless anyone thinks otherwise ...

> Change the array to slice to fix compile issue:
> 
> ```rust
> let want = &[32, 0 ...] as &[_];
> ```

Oh nice, thanks.

**Comment by tcharding** [comment]
> I think we need one of the following:
> 
>     * move `tests/bincode` and `tests/hex` inside `test_data`
> 
>     * create `tests/data` and move `test_data`, `tests/bincode` and `tests/hex` inside it

Good suggestion, I elected to move the files from `test_data` to a newly created `tests/data/` directory.

File: tests/regression_opcodes.rs [hunk 2]
```diff
@@ -0,0 +1,276 @@
+//! serde regression tests for blockdata::opcodes module.
```
Comment (Kixunil) [inline tests/regression_opcodes.rs:1]: Also better rename the file and use inner cfg.

File: tests/regression_opcodes.rs [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+    regression!(OP_RETURN_247, "OP_RETURN_247");
+    regression!(OP_RETURN_248, "OP_RETURN_248");
+    regression!(OP_RETURN_249, "OP_RETURN_249");
+    regression!(OP_RETURN_250, "OP_RETURN_250");
+    regression!(OP_RETURN_251, "OP_RETURN_251");
+    regression!(OP_RETURN_252, "OP_RETURN_252");
+    regression!(OP_RETURN_253, "OP_RETURN_253");
+    regression!(OP_RETURN_254, "OP_RETURN_254");
+    regression!(OP_INVALIDOPCODE, "OP_INVALIDOPCODE");
+}
```
Comment (Kixunil) [inline tests/regression_opcodes.rs:276]: First of all, this comment is not very important, especially compared to the others.

Just noticed that every single output here is just stringification of the input. You could write this macro instead:

```rust
macro_rules! test_opcodes {
    ($($op:ident),* $(,)?) => {
        $(
            let op = bitcoin::blockdata::opcodes::all::$op;
            let want = concat!("\"", strigify!($op), "\"");
            let got = ::serde_json::to_string(&op).unwrap();
            assert_eq!(got, want, "Regression test failed for: {}", stringify!($op));
        )*
    }
}

test_opcodes! {
    OP_PUSHBYTES_0,
    OP_PUSHBYTES_1,
    // ...
}
```

Notes:
* I prefer to use macros with repeated inputs if I call them like this because it avoids useless repeating of macro name.
* Notice `stringify!()` macro
* I used `concat!()` instead of `format!()` because it's compile-time and hopefully runs the test faster which may be important, but TBH didn't measure. Could also make it slower if it's recompiled often and the compiler does more work because of it.
* Didn't use `concat!()` in `assert_eq` because it's in unlikely branch and format string is a bit more readable
* `Regression test failed for` message may be unneeded as one should see the opcode name in the `assert_eq` output ("right: ...")

File: tests/regression.rs [hunk 4]
```diff
@@ -0,0 +1,380 @@
...
+    let got = serialize(&script).unwrap();
+    let want = bincode_from_file("script");
+    assert_eq!(got, want)
+}
+
+#[test]
+#[cfg(feature = "serde")]
+fn serde_regression_txin() {
+    let s = include_str!("data/hex/txin");
+    let txin: TxIn = deserialize(&parse_hex(s)).unwrap();
```
Comment (Kixunil) [inline tests/regression.rs:82]: Why not just `include_bytes!()` and feed them in directly without decoding?

File: tests/regression.rs [hunk 5]
```diff
@@ -0,0 +1,380 @@
...
+    let name = format!("tests/data/bincode/{}", name);
+    let file = File::open(name).unwrap();
+    let reader = BufReader::new(file);
+
+    reader.lines().next().unwrap().unwrap()
+        .split(',').map(|s| s.trim())
+        .filter(|s| !s.is_empty())
+        .map(|s| s.parse().unwrap())
+        .collect()
+}
```
Comment (Kixunil) [inline tests/regression.rs:50]: Maybe store it as raw bytes and use `include_bytes!()` instead?

Anyway, since the file contains a single line using `std::fs::read_to_string()` would be simpler and faster.

File: tests/regression.rs [hunk 6]
```diff
@@ -0,0 +1,380 @@
...
+#[cfg(feature = "serde")]
+fn parse_hex(hex: &str) -> Vec<u8> {
+    Vec::from_hex(hex.trim()).unwrap()
+}
+
+/// Implicitly does regression test for `BlockHeader` also.
+#[test]
+#[cfg(feature = "serde")]
+fn serde_regression_block() {
+    let segwit = include_bytes!("data/testnet_block_000000000000045e0b1660b6445b5e5c5ab63c9a4f956be7e1e69be04fa4497b.raw").to_vec();
```
Comment (Kixunil) [inline tests/regression.rs:62]: Unneeded `to_vec()`

File: src/blockdata/block.rs [hunk 7]
```diff
@@ -400,7 +400,7 @@ mod tests {
     // Check testnet block 000000000000045e0b1660b6445b5e5c5ab63c9a4f956be7e1e69be04fa4497b
     #[test]
     fn segwit_block_test() {
-        let segwit_block = include_bytes!("../../test_data/testnet_block_000000000000045e0b1660b6445b5e5c5ab63c9a4f956be7e1e69be04fa4497b.raw").to_vec();
+        let segwit_block = include_bytes!("../../tests/data/testnet_block_000000000000045e0b1660b6445b5e5c5ab63c9a4f956be7e1e69be04fa4497b.raw").to_vec();
```
Comment (Kixunil) [inline src/blockdata/block.rs:403]: While you're at it I think you could remove `.to_vec()`.

**Review by Kixunil — COMMENTED** [review]
Did only a light review. Since this is not very urgent we can afford a bit of bikesheding, right?

File: tests/regression.rs [hunk 8]
```diff
@@ -0,0 +1,380 @@
...
+//!
+//! For remaining types see: ./regression_opcodes.rs
+//!
+//! If you find a type defined in `rust-bitcoin` that implements `Serialize` and does _not_ have a
+//! regression test please add it.
+//!
+//! Types/tests were found using, and are ordered by, the output of: `git grep -l Serialize`.
+//!
+
+#![allow(unused_imports)] // All imports are unused when use-serde feature is not set.
```
[the remark this answers is not in the document]
Comment (tcharding) [reply tests/regression.rs:11]: Face palm! So obvious now I read it :)

**Comment by tcharding** [comment]
> Since this is not very urgent we can afford a bit of bikesheding, right?

Bikeshed all day! Thanks for the review, I learned a bunch from this review.

File: tests/regression.rs [hunk 9]
```diff
@@ -0,0 +1,380 @@
+//! Regression tests for _most_ types that implement `serde::Serialize`.
```
[the remark this answers is not in the document]
Comment (tcharding) [reply tests/regression.rs:1]: Done, thanks.

File: tests/regression_opcodes.rs (hunk 2 above)
Comment (tcharding) [reply tests/regression_opcodes.rs:1]: Done, thanks.

File: tests/regression_opcodes.rs (hunk 3 above)
Comment (tcharding) [reply tests/regression_opcodes.rs:276]: Thanks for taking the time to explain this. Re last point; I checked, error is clear without the message.

File: tests/regression.rs (hunk 5 above)
Comment (tcharding) [reply tests/regression.rs]: Used both these ideas as suggested :)

File: src/blockdata/block.rs (hunk 7 above)
Comment (tcharding) [reply src/blockdata/block.rs:403]: Done, thanks.

File: tests/regression.rs (hunk 6 above)
Comment (tcharding) [reply tests/regression.rs]: Done, thanks.

File: tests/regression.rs (hunk 4 above)
Comment (tcharding) [reply tests/regression.rs]: Cool, so now I have binary data in the `tests/data/` directory and am using `include_bytes!`.  Makes the code a bit neater but I fear it makes adding new tests harder because I had to convert all the bincode integer arrays to binary. I've left in a helper function for doing so for other devs (or future Tobin).

File: src/blockdata/block.rs (hunk 7 above)
Comment (tcharding) [reply src/blockdata/block.rs:403]: Turns out this is needed for rust 1.29 unless we want to cast in the `assert_eq` statement at bottom of function. To be honest I find Rust 1.29 extremely annoying, sometimes I can build with it other times I cannot so I just left this as is.

FTR I'm using this
```
build-with-rust-1.29 () {
    cargo clean
    rm -f Cargo.lock
    cargo +1.29 generate-lockfile --verbose && cargo +1.29 update -p cc --precise "1.0.41" --verbose
    cargo +1.29 build --features=use-serde
}
```
But it only works sometimes, other times I get errors like this
```
Updating cc v1.0.72 -> v1.0.41
error: unable to get packages from source

Caused by:
failed to parse manifest at `/home/tobin/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.36/Cargo.toml`

Caused by:
editions are unstable

Caused by:
feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
``` 
Any tips most appreciated.

Comment (tcharding) [reply src/blockdata/block.rs:403]: oh I worked it out, I needed 
```
    cargo +1.29 generate-lockfile --verbose && \
        cargo +1.29 update -p cc --precise "1.0.41" --verbose && \
        cargo +1.29 update --package "serde" --precise "1.0.98" --verbose && \
        cargo +1.29 update -p "serde_derive" --precise "1.0.98" --verbose
```

File: tests/regression.rs (hunk 4 above)
Comment (Kixunil) [reply tests/regression.rs]: How about adding a simple shell script as an external too? Or if it's too involved for a shell script, [cargo xtask](https://github.com/matklad/cargo-xtask)

File: tests/serde.rs [hunk 10]
```diff
@@ -0,0 +1,352 @@
...
+    let want = include_bytes!("data/serde/uint128_bincode");
+    assert_eq!(got, want)
+}
+
+/// Helper function to create binary data from debug output.
+///
+/// Reads a comma separated list of integers from file `/tmp/<name>` into a vector and writes it as
+/// binary data to `/tmp/<name>_bincode`. The integers represent the expected bincode for a
+/// serialized data type.
+#[allow(dead_code)]
```
Comment (Kixunil) [inline tests/serde.rs:336]: I really don't like having this in tests, could you move it to a separate tool?

Comment (tcharding) [reply tests/serde.rs:336]: Yeah sure thing, I was kind of feeling the same when I committed it but couldn't think of a better place. Will think a bit harder. Thanks

Comment (tcharding) [reply tests/serde.rs:336]: I added a file `util.sh`, put the function in there, improved it a bit, and added documentation on its use to the top of `serde.rs`.

File: tests/regression.rs (hunk 4 above)
Comment (tcharding) [reply tests/regression.rs]: I think I've addressed this by moving the utility function to `util.rs`. With the docs I added its pretty easy to add new tests now.

File: tests/util.rs [hunk 11]
```diff
@@ -0,0 +1,14 @@
+use std::fs::OpenOptions;
```
Comment (Kixunil) [inline tests/util.rs:1]: I have strong dislike for the name "util" (or "misc" and in some cases "lib") because it doesn't convey information. I think `create_bincode_file.rs` would be a good name but feel free to suggest other.

File: tests/util.rs [hunk 12]
```diff
@@ -0,0 +1,14 @@
...
+
+/// Creates a file at `path` and writes binary `data` to it.
+///
+/// This can be used to create binary bincode data files as is done in
+/// `rust-bitcoin/tests/data/serde`. Pass in the output of serde serialization as `data`.
+pub fn create_bincode_file<P: AsRef<Path> + ?Sized>(data: &[u8], path: &P) -> Result<(), io::Error>{
+    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
+    file.write_all(&data)?;
+    Ok(())
+}
```
Comment (Kixunil) [inline tests/util.rs:14]: This writes arbitrary data, not specifically bincode and looks like the only difference from `std::fs::write` is `create_new(true)`. I wonder if it being present could create more noise than value...

Comment (tcharding) [reply tests/util.rs:14]: lol, I thought this exact thing myself after trimming the function down.  While writing a response just now I realized that it would be just as good to put the two lines of code into the comment at the head of the file and remove this all together. Sorry for the noise, totally should have thought of that before.

Comment (Kixunil) [reply tests/util.rs:14]: No problem!

**Comment by tcharding** [comment]
Converting to draft while we do the MSRV bump shenanigans.

**Comment by apoelstra** [comment]
Nice! I read through the code and this looks great as of 3bbfce7b5beabf651a7e65fd0f869c63670bae0e. I didn't look at any of your test data but I assume that if it passes it passes.

Having said this I can't figure out how to actually run these tests.

**Comment by tcharding** [comment]
> Having said this I can't figure out how to actually run these tests.

`cargo test --features=use-serde`  (you definitely owe me a beer for this one :)

or for just the tests in `tests/serde.rs`, I prefixed them all with `serde_regression`

`cargo test --features=use-serde serde_regression`

**Review by apoelstra — APPROVED** [review]
ACK c3b2157603a947c94fe7caa7752eae3c87483108

**Review by apoelstra — COMMENTED** [review]
Thanks! I should've been able to figure that out :P

File: Cargo.toml [hunk 13]
```diff
@@ -9,7 +9,6 @@ documentation = "https://docs.rs/bitcoin/"
 description = "General purpose library for using and interoperating with Bitcoin and other cryptocurrencies."
 keywords = [ "crypto", "bitcoin" ]
 readme = "README.md"
-exclude = ["./test_data"]
```
Comment (Kixunil) [inline Cargo.toml:12]: Why? AFAIR it was previously excluded so that people using the library don't have to download the test data and development happens on top of cloned git repo anyway. Is there a new argument?

Comment (tcharding) [reply Cargo.toml:12]: Ah, during rebase the `test_data` directory came back into existence, thanks for flagging this. To answer your question, after I force push, the `test_data` directory will no longer exist, patch 1 of this PR moves its contents to `tests/data` - hence removal of the exclude line.

**Comment by tcharding** [comment]
Force push rebases and changes patch 1 to move _all_ the contents of `test_data` to `tests/data`. (Please note one test data file was not being used so is removed all together, `psbt_combined.hex`. This is because it is the same psbt as psbt2.hex.

**Review by apoelstra — DISMISSED** [review]
ACK a49055b64305e0e4fc9e55aad64c0a186577710e

File: Cargo.toml (hunk 13 above)
Comment (Kixunil) [reply Cargo.toml:12]: In that case `exclude` should be changed, not removed. Am I still missing something?

Comment (tcharding) [reply Cargo.toml:12]: We don't think we need an explicit exclude for `tests/` since its the standard directory name for integration tests.

Comment (tcharding) [reply Cargo.toml:12]: Excuse the late reply, missed your comment previously.

Comment (Kixunil) [reply Cargo.toml:12]: Yes, `tests/` is standard directory but `test/data` may be just too much for non-crate-developers. (But perhaps even remove `tests/`?)

Comment (tcharding) [reply Cargo.toml:12]: Oh, on further reading I think you are correct. I'll exclude `tests/`. Thanks.

**Comment by tcharding** [comment]
Changes in force push: In the first patch add to the manifest `exclude = "./tests"`.

**Comment by tcharding** [comment]
And use the correct form ``exclude = ["./tests"]`.

**Comment by tcharding** [comment]
Requires https://github.com/rust-bitcoin/rust-bitcoin/pull/1083 to pass CI.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK ec276b5fa8d4cf35e97150944def4b5b76bd2dae

**Comment by tcharding** [comment]
Friendly bump please crew.

**Comment by sanket1729** [comment]
I would appreciate it if someone else gave a second ACK for this PR. I don't have much experience with serde and somewhat dislike reviewing the code that touches that.

If this is blocked on the second ACK by the month end. I don't mind learning a thing or two in order to review this PR.

**Comment by apoelstra** [comment]
@sanket1729 I don't think you really need to understand serde beyond "it lets you serialize stuff as json" to understand the PR. The vast majority of changes here are just added test vectors, and you don't need to spend much time reviewing those because their purpose is just to catch regressions from the current behavior.

**Review by sanket1729 — DISMISSED** [review]
ACK ec276b5fa8d4cf35e97150944def4b5b76bd2dae. @apoelstra, should have actually read the PR. I was scared of 700-line diff serde code, but this was easier than expected.

**Comment by sanket1729** [comment]
This cannot be merged cleanly, strange that github does not point it out.

```
~/bitcoin-maintainer-tools/github-merge.py 724
CONFLICT (file location): test_data/legacy_sighash.json added in HEAD inside a directory that was renamed in pull/724/head, suggesting it should perhaps be moved to tests/data/legacy_sighash.json.
Removing test_data/psbt_combined.hex
Auto-merging src/util/taproot.rs
Auto-merging src/util/sighash.rs
Auto-merging src/util/psbt/mod.rs
Auto-merging src/util/hash.rs
Auto-merging src/util/bip158.rs
Auto-merging src/network/message.rs
Auto-merging src/blockdata/block.rs
Auto-merging Cargo.toml
Automatic merge failed; fix conflicts and then commit the result.
ERROR: Cannot be merged cleanly.

```

**Comment by tcharding** [comment]
Changes in force push:
- Audited codebase for new types that may have been missed when I originally did this work, adding tests as needed (`LockTime`,  `TaprootSpendInfo` )
- FIxed broken data (types changed since original work done)

Note, there are a bunch of types that are not explicitly tested but are tested as part of a parent struct. This is not documented and may not be trivial to verify - do we want to do better?

**Comment by tcharding** [comment]
Force push to trigger CI, not sure why its not running.

**Comment by apoelstra** [comment]
> Note, there are a bunch of types that are not explicitly tested but are tested as part of a parent struct. This is not documented and may not be trivial to verify - do we want to do better?

I'm willing to just live with the situation -- the current PR clearly tests a large swath of types and we can add tests in the future if it turns out we missed something. (I think PRs that change serde impls are pretty conspicuous so we'd probably check then whether the relevant tests are present ... or worst case we'll get bug reports.)

**Review by apoelstra — DISMISSED** [review]
ACK 33ca78ccac4cc801334b3b8bae7b3d348b8443fa

**Comment by tcharding** [comment]
Rebase to pick up recent fuzzer change.

**Review by apoelstra — DISMISSED** [review]
ACK 3ef6935149892e6ab7c6320606f4fbe593d262bc

File: tests/data/serde/README.md [hunk 14]
```diff
@@ -0,0 +1,12 @@
+Serialization input/output
+==========================
+
+Files here contain hex strings and binary data representing types used for
+regression testing.
+
+- *_hex: consensus encoded types represented as hex strings
```
Comment (Kixunil) [inline tests/data/serde/README.md:7]: Why do we need `_hex` files? Shouldn't we test hex decoding separately?

**Review by Kixunil — COMMENTED** [review]
Can't do a full review RN just note that I'd prefer having *short* test *strings* (e.g. hex public key) inline in tests. At least unless they are some shared canonical test vectors. Wouldn't block the PR for that though.

File: tests/data/serde/README.md (hunk 14 above)
Comment (apoelstra) [reply tests/data/serde/README.md:7]: TBH I'd rather drop the binary vectors than the hex ones.

Agreed that they're pretty-much redundant and we shouldn't duplicate everything.

Comment (tcharding) [reply tests/data/serde/README.md:7]: hmm, I can't really remember why I put some in hex (I did the bulk of this work in November last year) but my guess was that I was lazy and just used hex strings when they appeared elsewhere in the codebase (the binary stuff I generated for each type manually). I do remember going through at the end and moving the hex stuff to files instead of inline. My reasoning was that the data is not meaningful so better to conceal it in a file and keep the test source code clean. I can't remember why I used binary instead of hex for the manually generated types, perhaps because we have the two blocks there in `tests/data` that are in binary - if we move to hex we should be uniform. We exclude the `tests/` directory in `Cargo.toml` so data size is not a consideration. I do not know what other trade offs there are between the two?

Comment (apoelstra) [reply tests/data/serde/README.md:7]: I think it's fine -- usually they'll just be "parsing" the hex to a `Vec<u8>` then parsing from there as though it were binary data. And hex->byte vector is write-once code.

Comment (tcharding) [reply tests/data/serde/README.md:7]: Yesterday I forgot that the hex files hold hex that is consensus excodings, we are consensus deserialize them, serde serializing and then checking the serder serializaiton (using `bincode` crate) against the data in the _bincode files. Are you guys happy with this method?

An alternate method would be have a single hex file and serde deserialize it, serde serialize it, an compare - I do not know if one method is better than the other but my gut feel is that the current method is better.

I want to confirm before changing everything please because this PR is as boring to work on as it is to review :)

Comment (Kixunil) [reply tests/data/serde/README.md:7]: I think it makes sense to do cross-serialization tests so that if there was the same bug in serde serailization and deserialization it wouldn't be missed. So no change in method. If you both prefer hex to binary it's OK.

Comment (tcharding) [reply tests/data/serde/README.md:7]: So do you want me to remove the use of `bincode` crate for doing serde serialization @apoelstra and use the `hex` crate instead?

Comment (apoelstra) [reply tests/data/serde/README.md:7]: We should never need the `hex` crate.

We should probably add a `deserialize_hex` method analogous to `serialize_hex` which uses the `bitcoin_hashes::hex` module.

Comment (tcharding) [reply tests/data/serde/README.md:7]: I don't get it, we are explicitly trying to test the serde implementations, we have to use a crate serializes using serde to do so, right?

**Review by sanket1729 — DISMISSED** [review]
reACK 3ef6935149892e6ab7c6320606f4fbe593d262bc

File: tests/data/serde/README.md (hunk 14 above)
Comment (apoelstra) [reply tests/data/serde/README.md:7]: I was not aware that `hex` uses serde. What serialization format does it use?

Comment (tcharding) [reply tests/data/serde/README.md:7]: Looks like it just serializes as ascii chars: https://docs.rs/hex/latest/hex/serde/fn.serialize.html

Comment (Kixunil) [reply tests/data/serde/README.md:7]: It's simple enough for us to NIH it.

**Comment by apoelstra** [comment]
We have two ACKs but I'm not clear whether we want to modify this PR to answer "what should we be doing about hex vs binary" question here.

**Comment by tcharding** [comment]
> I'm not clear whether we want to modify this PR to answer "what should we be doing about hex vs binary" question here.

I am unclear also.

**Comment by Kixunil** [comment]
When in doubt I usually prefer "make some progress unless this affects API". This already improves things from previous state of the code and we can resolve the remaining issues later.

Unfortunately this needs rebase.

**Comment by tcharding** [comment]
Rebased and used qualified path for `LockTime` and `PackedLockTime`.

**Review by apoelstra — DISMISSED** [review]
ACK 9a4c79a390bcedcb78c65a5688f269c36f090823

**Comment by tcharding** [comment]
Rebased and added tests for `Work`, `Target`, `relative::LockTime` types (`Height` and `Time` incl.)

**Comment by tcharding** [comment]
FTR I have no clue if this covers _all_ types since its been open for so long, I'm not super enthusiastic about auditing again while the PR is open, if/when it merges I can re-audit the whole codebase though.

**Review by apoelstra — DISMISSED** [review]
ACK 16fd5f6e8160317b7053b74dc12a1692f1d94475

**Comment by tcharding** [comment]
Re-base and remove the patch to move test data since its on master already.

**Review by apoelstra — APPROVED** [review]
ACK 962abcc963f8819efb338fba2b43b471297bd3d8

**Review by sanket1729 — APPROVED** [review]
ACK 962abcc963f8819efb338fba2b43b471297bd3d8. This has been open for a long time. Merging this in the interest of progress.
