### PR TITLE
Make code style consistent and fix naming in macro Array implementations

### LINKED ISSUE #4210: amount: Make usage of `Self` and type uniform across both modules
After #4157.

Make all the functions identical across both `signed` and `unsigned` modules

e.g., 'fn foo(&self) -> Self` vs `fn foo(&self) -> Amount`.

### LINKED ISSUE #4241: The `impl_try_from_array` macro is named incorrectly
It's implementing `From`, not `TryFrom`, so it should be named `impl_from_array`.

### PR DESCRIPTION
**Pull request by erickcestari**
This PR makes two main changes:

1. Standardizes the function signatures in the `Amount` and `SignedAmount` implementations by consistently using `Self` as the return type instead of the concrete type names. This improves code consistency, maintainability, and follows Rust's idiomatic practices.
2. Renames `impl_try_from_array` to `impl_from_array` to better reflect its functionality.

### Changes
**Consistent usage of Self instead of concrete types**

- Replace all occurrences of `-> Amount` with `-> Self `in unsigned.rs
- Replace all occurrences of `-> SignedAmount` with `-> Self` in signed.rs
- Make similar replacements for Option/Result return types
- Use `Self::` instead of explicit type name for static method calls

**Function rename**

Renamed `impl_try_from_array` to `impl_from_array` for better clarity

### Related Issues

Closes #4210

Closes #4241

### CODE REVIEW

File: bitcoin/src/taproot/merkle_branch/buf.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ impl_try_from!(&[TapNodeHash]);
 impl_try_from!(Vec<TapNodeHash>);
 impl_try_from!(Box<[TapNodeHash]>);
 
-macro_rules! impl_try_from_array {
+macro_rules! impl_from_array {
```
Comment (Kixunil) [inline bitcoin/src/taproot/merkle_branch/buf.rs:129]: Thanks, though I planned to join it with the other macro. Not a big deal, I'll do it later.

**Review by Kixunil — APPROVED** [review]
ACK e744347022d1ad1e0ca0a83ec9350501af08297b

**Comment by yancyribbens** [comment]
Concept ACK

**Review by tcharding — APPROVED** [review]
ACK e744347022d1ad1e0ca0a83ec9350501af08297b

**Review by apoelstra — APPROVED** [review]
ACK e744347022d1ad1e0ca0a83ec9350501af08297b; successfully ran local tests
