### PR TITLE
Followups to #4998 (fix TransactionDecoder)

### LINKED ISSUE #5122: consensus_encoding: Improve `Transaction` decoder state machine
See if we can't improve the transaction state machine to be less panicky and indirect and full of "copy this to get mutable access" patterns (I spent a bit of time on this but don't have a complete solution).

This is a follow up to #4998, original post: https://github.com/rust-bitcoin/rust-bitcoin/pull/4998#issuecomment-3394803058

### LINKED ISSUE #5125: Fix `Decoder::end` impl on `Transaction`
`Transaction` decoder impl of `Decoder::end` is incorrect because it does not panic/error as described in the trait method docs.

This is a follow up to #4998, original comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/4998#issuecomment-3394846401

### PR DESCRIPTION
**Pull request by apoelstra**
Refactors the `TransactionDecoder` state machine in a couple ways, eliminating some unreachable panic paths and also eliminating most of the reachable panic paths in `end()` (which should have been error returns).

Fixes two of the four followup issues to #4998 -- the other two are optimizing `OutpointDecoder` which is non-essential/low-priority, and eliminating the `From` impls required by the composite `Decoder` types (which is a somewhat-hard API problem and I don't think we want to hold up the rc on it).

Fixes #5125
Fixes #5122

### CODE REVIEW

File: primitives/src/transaction.rs [hunk 1]
```diff
@@ -433,25 +388,52 @@ impl Decoder for TransactionDecoder {
...
-                    let attempt = *attempt;
+                },
+                State::Done(..) => return Ok(false),
+                State::Transitioning => {
+                    panic!("use of decoder in transitioning state");
+                }
+            }
 
-                    let decoder = self.state.inputs_transition();
+            // If the above failed, end the current decoder and go to the next state.
```
Comment (nyonson) [inline primitives/src/transaction.rs:428]: nit: the "failed" in this comment and "success" up on line 391 had me a little confused thinking it was an error. FWIW I thought of the success as "more bytes required" and failure as "sufficient bytes for next state".

Comment (apoelstra) [reply primitives/src/transaction.rs:428]: Hmm, yeah, that's a good way of looking at it. I was thinking of it like "succeeded means we're done for now".
