### PR TITLE
Unify `TapLeafHash` and `TapBranchHash` into `TapNodeHash` while tree construction

### LINKED ISSUE #1393: TapTweak API for a single script path spending case
Correct me if I'm wrong, but taproot script tree with a for single script path spending condition we will have a merkle root as a hash of that leaf script. In order to construct output key in such cases we can't provide a merkle root value in the existing API in a type-safe way.

https://github.com/rust-bitcoin/rust-bitcoin/blob/60f3a19acd34e1654aed21ec103ef0e34b714e0d/bitcoin/src/util/schnorr.rs#L126

### PR DESCRIPTION
**Pull request by sanket1729**
This does not completely fix #1393 but is a simple starter. Unfortunately, we still need hash_new_type for `TapNodeHash` because is exported as the Merkle root in taproot psbt. This requires serialization and display/from_str methods.

This also adds a method 1) `TapNodeHash::from_script` to deal with single leaf case cleanly. As a nice side effect, this removes the ugly uses of `sha256::Hash` that I had used to represent both `TapLeafHash` and `TapBranchHash`

Does not fix
1) Exporting `TapTweakHash`. This requires some changes to macros we use.
2) Safer usage of `TapNodeHash` by not making it `hash_new_type` and having guarded constructors. As mentioned above, this is required for psbts and sharing Merkle roots. Perhaps, we might need a new type while constructing trees that is not `hash_new_type`, and convert it to another type that represents the final Merkle root. 

My overall feeling is that this is best addressed with more examples than changing and complicating existing code. 

I don't feel strongly about the rename, so can go back if `TapBranchHash` instead of `TapNodeHash`.

### CODE REVIEW

**Comment by Kixunil** [comment]
Oh, yeah, I wanted to open #1481 before but didn't have time and forgot. Id should completely resolve the issue you found.

File: bitcoin/src/taproot.rs [hunk 1]
```diff
@@ -622,16 +630,14 @@ impl ScriptLeaf {
 }
```
Comment (Kixunil) [inline bitcoin/src/taproot.rs:630]: Shouldn't `ScriptLeaf::leaf_hash` return `TapNodeHash`? Do we even need `TapLeafHash` for anything now?

**Review by Kixunil — COMMENTED** [review]
Have to run so not a deep review but looks mostly fine.

File: bitcoin/src/taproot.rs (hunk 1 above)
Comment (sanket1729) [reply bitcoin/src/taproot.rs:630]: We need `TapLeafHash` in taproot sign APIs. https://docs.rs/bitcoin/latest/bitcoin/util/sighash/struct.SighashCache.html#method.taproot_signature_hash

Comment (Kixunil) [reply bitcoin/src/taproot.rs:630]: Oh, right, in that case we should also have a trivial `impl From<TapLeafhash> for TapNodehash`.

**Comment by apoelstra** [comment]
This is really cool! It's a lot cleaner, both conceptually and code-wise, than I'd feared from the discussion in #1393.

File: bitcoin/src/taproot.rs [hunk 2]
```diff
@@ -111,18 +115,23 @@ impl From<&ScriptLeaf> for TapLeafHash {
...
             eng.input(&b);
             eng.input(&a);
         };
-        TapBranchHash::from_engine(eng)
+        TapNodeHash::from_engine(eng)
+    }
+
+    /// Computes the [`TapNodeHash`] from a script and a leaf version.
+    pub fn from_script(script: &Script, ver: LeafVersion) -> TapNodeHash {
+        TapNodeHash::from_inner(TapLeafHash::from_script(script, ver).into_inner())
```
Comment (apoelstra) [inline bitcoin/src/taproot.rs:134]: In e03b9457111848cb26f3764b2d9cdc9d9ea21534:

Can you add a comment here highlighting that you're actually casting between two hash types here, since it's maybe hard to see in the `from_inner(X.into_inner())` form, explaining that this is because *leaves* of a taptree use a different hash prefix than the *internal nodes*, but the Merkle tree logic does not care about the distinction. Maybe also link to the BIP and/or to #1393.

I think a regular comment is fine, no need to doccomment this, since it's an internal implementation detail.

Comment (apoelstra) [reply bitcoin/src/taproot.rs:134]: Also, I agree with Kix's suggestion below that we add a conversion method from `TapLeafHash` to `TabBranchHash`, so this line can be simplified to `TapLeafHash::from_script(script, ver).into()`.

File: bitcoin/src/taproot.rs [hunk 3]
```diff
@@ -49,19 +49,23 @@ const MIDSTATE_TAPSIGHASH: [u8; 32] = [
...
-    doc="Taproot-tagged hash for tapscript Merkle tree leafs", false
+    doc="Taproot-tagged hash with tag \"TapLeaf\". This is used for computing tapscript
+    script spend hash.", false
 );
 #[rustfmt::skip]
-sha256t_hash_newtype!(TapBranchHash, TapBranchTag, MIDSTATE_TAPBRANCH, 64,
-    doc="Taproot-tagged hash for tapscript Merkle tree branches", false
+sha256t_hash_newtype!(TapNodeHash, TapBranchTag, MIDSTATE_TAPBRANCH, 64,
+    doc="Taproot-tagged hash with tag \"TapBranch\". This hash type is used while constructing
+    a taproot tree.", false
```
Comment (apoelstra) [inline bitcoin/src/taproot.rs:58]: In 6609dae247e9ac63c2a1d357183c93a55e4fb1af:

This doccomment should be updated to say that it might be tagged either with `TapBranch` or with `TapLeaf`; or maybe it should not mention this at all and just say "tagged hash used in taproot trees; see BIP-340 for tagging rules"

**Comment by sanket1729** [comment]
Rebased and ready for review

File: bitcoin/src/taproot.rs (hunk 2 above)
Comment (sanket1729) [reply bitcoin/src/taproot.rs:133]: Adressed

File: bitcoin/src/taproot.rs [hunk 4]
```diff
@@ -49,19 +49,22 @@ const MIDSTATE_TAPSIGHASH: [u8; 32] = [
...
 sha256t_hash_newtype!(TapTweakHash, TapTweakTag, MIDSTATE_TAPTWEAK, 64,
-    doc="Taproot-tagged hash for public key tweaks", false
+    doc="Taproot-tagged hash with tag \"TapTweak\". This hash type is used while computing
+    the tweaked public key", false
 );
 #[rustfmt::skip]
 sha256t_hash_newtype!(TapSighashHash, TapSighashTag, MIDSTATE_TAPSIGHASH, 64,
-    doc="Taproot-tagged hash for the taproot signature hash", false
+    doc="Taproot-tagged hash with tag \"TapSighash\". This hash type is used for computing
+    taproot signature hash.", false
```
Comment (Kixunil) [inline bitcoin/src/taproot.rs:67]: Could you try splitting "This hash type..." in these two into a separate paragraph to improve the doc?

File: bitcoin/src/taproot.rs (hunk 2 above)
Comment (Kixunil) [reply bitcoin/src/taproot.rs:133]: Since there's `From` now we might as well use it here?

File: bitcoin/src/taproot.rs [hunk 5]
```diff
@@ -544,15 +556,14 @@ pub struct NodeInfo {
 impl NodeInfo {
     /// Creates a new [`NodeInfo`] with omitted/hidden info.
     pub fn new_hidden_node(hash: sha256::Hash) -> Self {
```
Comment (Kixunil) [inline bitcoin/src/taproot.rs:558]: This should accept `TapNodeHash`. Or am I missing something? (Only this one is blocking.)

**Review by Kixunil — CHANGES_REQUESTED** [review]
Mostly nits, just one somewhat important thing.

File: bitcoin/src/taproot.rs (hunk 5 above)
Comment (sanket1729) [reply bitcoin/src/taproot.rs:558]: Duh, I swear all instances of sha256::Hash in this PR, but looks like I screwed up in rebasing somewhere

File: bitcoin/src/taproot.rs [hunk 6]
```diff
@@ -1064,15 +1062,17 @@ impl fmt::Display for TaprootError {
                 "Merkle Tree depth({}) must be less than {}",
                 d, TAPROOT_CONTROL_MAX_NODE_COUNT
             ),
-            TaprootError::InvalidTaprootLeafVersion(v) =>
-                write!(f, "Leaf version({}) must have the least significant bit 0", v),
+            TaprootError::InvalidTaprootLeafVersion(v) => {
```
Comment (sanket1729) [inline bitcoin/src/taproot.rs:1065]: A couple formatting changes got sneaked in here. Don't think it should be an issue

**Review by sanket1729 — COMMENTED** [review]
Ready for review again

File: bitcoin/src/taproot.rs [hunk 7]
```diff
@@ -49,19 +49,22 @@ const MIDSTATE_TAPSIGHASH: [u8; 32] = [
...
 sha256t_hash_newtype!(TapTweakHash, TapTweakTag, MIDSTATE_TAPTWEAK, 64,
-    doc="Taproot-tagged hash for public key tweaks", false
+    doc="Taproot-tagged hash with tag \"TapTweak\".
+    This hash type is used while computing the tweaked public key", false
 );
 #[rustfmt::skip]
 sha256t_hash_newtype!(TapSighashHash, TapSighashTag, MIDSTATE_TAPSIGHASH, 64,
-    doc="Taproot-tagged hash for the taproot signature hash", false
+    doc="Taproot-tagged hash with tag \"TapSighash\".
+    This hash type is used for computing taproot signature hash.", false
```
Comment (Kixunil) [inline bitcoin/src/taproot.rs:67]: I think there should be an empty line, but since I'm too tired to check myself, I will ignore this nit. We can fix later.

**Review by Kixunil — APPROVED** [review]
ACK f39cd88f5f711ff306f3e2272350a8ea07af6b35

**Review by tcharding — APPROVED** [review]
ACK f39cd88f5f711ff306f3e2272350a8ea07af6b35
