### PR TITLE
Fix wrong newtype APIs

### LINKED ISSUE #1336: Completely wrong implementation of `From` in `impl_array_newtype`
NO, NO, NO, NO, NO!!!! This is completely wrong implementation of `From`. Should've been `TryFrom` or `From<[$ty; $len]>`

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/1293#discussion_r1001724546_

### PR DESCRIPTION
**Pull request by Kixunil**
This fixes several API bugs:

* Use `TryFrom` instead of `From` for fallible conversions
* Move byte conversion methods from `impl_array_newtype` to `impl_bytes_newtype`
* Add missing trait impls like `AsRef`, `Borrow`, their mutable versions and infallible conversions from arrays

Closes #1336

Notably this change is much less bad than even I expected and some places actually get cleaner than before.

### CODE REVIEW

File: bitcoin/src/psbt/map/global.rs [hunk 1]
```diff
@@ -149,7 +149,7 @@ impl PartiallySignedTransaction {
                                 }
                                 let derivation = DerivationPath::from(path);
                                 // Keys, according to BIP-174, must be unique
-                                if xpub_map.insert(xpub, (Fingerprint::from(&fingerprint[..]), derivation)).is_some() {
+                                if xpub_map.insert(xpub, (Fingerprint::from(fingerprint), derivation)).is_some() {
                                     return Err(encode::Error::ParseFailed("Repeated global xpub key"))
```
Comment (Upasana33) [inline bitcoin/src/psbt/map/global.rs:153]: I think there are two missing tests that need to be checked

**Review by tcharding — APPROVED** [review]
ACK 64f7d2549ed29bd290a8d7a3aeb4a3b2c51f2a50

File: bitcoin/src/psbt/map/global.rs (hunk 1 above)
Comment (Kixunil) [reply bitcoin/src/psbt/map/global.rs:153]: Unrelated but which ones? Why do you think?

**Review by sanket1729 — APPROVED** [review]
code review ACK 64f7d2549ed29bd290a8d7a3aeb4a3b2c51f2a50

**Review by apoelstra — APPROVED** [review]
ACK 64f7d2549ed29bd290a8d7a3aeb4a3b2c51f2a50
