### PR TITLE
Fix all the lint warnings on 0.32.x branch

### LINKED ISSUE #5281: Lint `0.32.x` banch
`rust-bitcoin 0.32` is an LTS release, as such we will be backporting all sorts of things. It would be nice if the branch linted cleanly to make doing so easier / more pleasurable.

### PR DESCRIPTION
**Pull request by jamillambert**
See #5281 for reason.

Use the current version of nightly on master (2025-09-26) to lint and format the v0.32.x branch.

Fix all of the lint errors.

Run the formatter.

Fix some rustdoc issues.

Closes #5281

### CODE REVIEW

**Comment by jamillambert** [comment]
I grouped all of the similar lints together. This was a lot easier with jj than it would have been with just git. Clippy gives you a couple of random lint errors, you fix them and then get another random set - rinse and repeat. Then at the end CI says there are doc issues.

**Comment by tcharding** [comment]
> I grouped all of the similar lints together. This was a lot easier with jj than it would have been with just git. Clippy gives you a couple of random lint errors, you fix them and then get another random set - rinse and repeat. Then at the end CI says there are doc issues.

chuckle, yep sometimes the tools get in the way of the task. If I was better I'd put effort into `cargo` and `clippy` dev but I don't so I'm glad we have what we have.

**Comment by tcharding** [comment]
nit: I dunno if this is a backport. Its 'fix all the lint warnings on 0.32.x branch', right?

I guess many of the same changes are also on master, so it doesn't really matter.

**Comment by tcharding** [comment]
Thanks for doing this BTW, while reviewing I thought to myself "glad I didn't do this it would have annoyed me because I've fixed many of the things before"

**Comment by jamillambert** [comment]
> nit: I dunno if this is a backport. Its 'fix all the lint warnings on 0.32.x branch', right?
> 
> I guess many of the same changes are also on master, so it doesn't really matter.

Yeah I wasn't sure, I added it to make it clear the target branch was 0.32.x and not master. I have changed it to your suggestion.

**Comment by apoelstra** [comment]
In daad815b5d67dc028e39b92b2035371aec3e9724

So, this "broken links" thing is what `doc_auto_cfg` was for. There is a new flag, `doc_cfg` or something like that. I really really distrust docs.rs after they broke the entire fucking ecosystem with these flags and I don't want to use anything related to them anymore, but I believe it would be more "correct" to do so. Thoughts?

**Comment by jamillambert** [comment]
I removed `#![allow(rustdoc::broken_intra_doc_links)]` and instead wrote out the link in the rustdocs so that it still builds the docs when the `ordered` feature is not enabled.

File: bitcoin/src/blockdata/locktime/absolute.rs [hunk 1]
```diff
@@ -39,7 +39,7 @@ pub use units::locktime::absolute::{
 /// ordering on locktimes. We therefore have implemented [`PartialOrd`] but not [`Ord`].
 /// For [`crate::Transaction`], which has a locktime field, we implement a total ordering to make
 /// it easy to store transactions in sorted data structures, and use the locktime's 32-bit integer
-/// consensus encoding to order it. We also implement [`ordered::ArbitraryOrd`] if the "ordered"
+/// consensus encoding to order it. We also implement [`ordered::ArbitraryOrd`](https://docs.rs/ordered/latest/ordered/trait.ArbitraryOrd.html) if the "ordered"
```
Comment (tcharding) [inline bitcoin/src/blockdata/locktime/absolute.rs]: This line is too long. Can we use the style where at the bottom of the block of docs put

```rust
///
/// [`ordered::ArbitraryOrd`]: <https://docs.rs/ordered/latest/ordered/trait.ArbitraryOrd.html>
```

Comment (jamillambert) [reply bitcoin/src/blockdata/locktime/absolute.rs]: Done.

**Comment by tcharding** [comment]
> In [daad815](https://github.com/rust-bitcoin/rust-bitcoin/commit/daad815b5d67dc028e39b92b2035371aec3e9724)
> 
> So, this "broken links" thing is what `doc_auto_cfg` was for. There is a new flag, `doc_cfg` or something like that. I really really distrust docs.rs after they broke the entire fucking ecosystem with these flags and I don't want to use anything related to them anymore, but I believe it would be more "correct" to do so. Thoughts?

I'm not sure if I just 'worked out' what you already said or not but #5307

**Comment by apoelstra** [comment]
Sorry for the delays. I'll make it my top rust-bitcoin priority today to get my local CI to pass on the tip of this so we can merge it then get the other backports merged.

**Comment by apoelstra** [comment]
Don't have to deal with it in this PR but note that generate-files.sh is out of date here as well :P

**Comment by apoelstra** [comment]
utACK a2fe08c9a9b661af2eda47bc09fe895d9b3bce22 ran my local CI on the tip
