### PR TITLE
Fix BIP32 validation for private keys and master key constraints (#4195)

### LINKED ISSUE #4195: `Xpriv::decode` doesn't check that 45th byte is 0
According to the BIP private keys use 0 at 45th byte (which makes them distinguishable from public keys that implicitly use 02 or 03) but the code does not check it it is so so it might accidentally decode a public key as if it was a private key.

FTR this was found by trying to convert the code to use array operations only that also prove that the entire array was consumed - and it proved it was not!

### PR DESCRIPTION
**Pull request by erickcestari**
This PR addresses issue #4195 by adding proper validation when decoding extended private keys:

### Changes

- Add validation to ensure byte 45 is zero as required by BIP-32 specification for private keys
- For master keys (depth=0), add validation to ensure parent fingerprint is zero
- For master keys (depth=0), add validation to ensure child number is zero
- Add corresponding error types to handle these validation failures
- Add unit tests to verify each validation rule

### Validation Rationale
These checks improve security by rejecting malformed extended keys that could potentially lead to unexpected behavior. As noted in the issue discussion, these validations are explicitly required by the BIP-32 specification.

### Testing
Added three new unit tests to verify each validation rule:

- test_reject_xpriv_with_non_zero_byte_at_index_45
- test_reject_xpriv_with_zero_depth_and_non_zero_index
- test_reject_xpriv_with_zero_depth_and_non_zero_parent_fingerprint

Fixes #4195

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 8f74b823ab8ef44bde7d003f8ba43fbe44dbef3e

File: bitcoin/src/bip32.rs [hunk 1]
```diff
@@ -1235,6 +1266,44 @@ mod tests {
                   "xpub68NZiKmJWnxxS6aaHmn81bvJeTESw724CRDs6HbuccFQN9Ku14VQrADWgqbhhTHBaohPX4CjNLf9fq9MYo6oDaPPLPxSb7gwQN3ih19Zm4Y");
     }
 
+    #[test]
+    fn test_reject_xpriv_with_non_zero_byte_at_index_45() {
+        let mut xpriv = base58::decode_check("xprv9wSp6B7kry3Vj9m1zSnLvN3xH8RdsPP1Mh7fAaR7aRLcQMKTR2vidYEeEg2mUCTAwCd6vnxVrcjfy2kRgVsFawNzmjuHc2YmYRmagcEPdU9").unwrap();
+
+        // Modify byte at index 45 to be non-zero (e.g., 1)
+        xpriv[45] = 1;
```
Comment (tcharding) [inline bitcoin/src/bip32.rs:1274]: nit: This comment says what the code does as opposed to why it does it. A more useful comment would say something like 'all xpriv keys must have a zero byte prefix'

File: bitcoin/src/bip32.rs [hunk 2]
```diff
@@ -1235,6 +1266,44 @@ mod tests {
...
+        assert!(result.is_err());
+
+        match result {
+            Err(Error::InvalidPrivateKeyPrefix) => {}
+            _ => panic!("Expected InvalidPrivateKeyPrefix error, got {:?}", result),
+        }
+    }
+
+    #[test]
+    fn test_reject_xpriv_with_zero_depth_and_non_zero_index() {
```
Comment (tcharding) [inline bitcoin/src/bip32.rs:1286]: nit: We don't tend to use the `test_` prefix on unit tests.

**Review by tcharding — APPROVED** [review]
Thanks man! I acked already. The nit comments are just for your information for future patches. No need to change the current PR IMO.

**Comment by jrakibi** [comment]
ACK 8f74b823ab8ef44bde7d003f8ba43fbe44dbef3e

**Review by apoelstra — APPROVED** [review]
ACK 8f74b823ab8ef44bde7d003f8ba43fbe44dbef3e; successfully ran local tests

File: bitcoin/src/bip32.rs [hunk 3]
```diff
@@ -699,6 +713,23 @@ impl Xpriv {
...
+        let depth = data[4];
+        if depth == 0 {
+            if !data[5..9].iter().all(|&b| b == 0) {
+                return Err(Error::NonZeroParentFingerprintForMasterKey);
+            }
+
+            if !data[9..13].iter().all(|&b| b == 0) {
+                return Err(Error::NonZeroChildNumberForMasterKey);
+            }
+        }
```
Comment (Kixunil) [inline bitcoin/src/bip32.rs:731]: As I understand it, these should also apply to xpubs, not just xprivs.

Comment (apoelstra) [reply bitcoin/src/bip32.rs:731]: Ah, yes, good catch!

We should just bring all of https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#test-vector-5 into our unit tests. (Arguably all the test vectors, but that one in particular would've caught this.)

Comment (Kixunil) [reply bitcoin/src/bip32.rs:731]: Yeah, that's what I'm working on.
