### PR TITLE
Fix Error type for SimpleDecoder and SimpleEncoder

### LINKED ISSUE #131: Pinning down an Error type for `SimpleDecoder` and `SimpleEncoder`
Per @apoelstra's [comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/103#discussion_r209456345), we should pin down an Error type for `SimpleDecoder` and `SimpleEncoder`. I believe we should define a type `network::serialize::Error` that is a variant of `util::Error`.

Why we shouldn't just use `util::Error`:

### Reason 1

It stops the overpopulation of `util::Error` variants.

### Reason 2

In files such as `script.rs`, if we did
```
use ::Error;
```
Such that we can do
```
fn consensus_decode(d: &mut D) -> Result<Script, Error> {
    ...
}
```
It would trigger a namespace conflict with `script::Error`.

Note: this is assuming that we do
```
pub use util::Error;
```
at the top-level `lib.rs`.

### PR DESCRIPTION
**Pull request by dongcarl**
- Separate serialize::Error and network::Error from util::Error
- Remove unneeded propagate_err and consume_err

Closes #131

### CODE REVIEW

File: src/network/mod.rs [hunk 1]
```diff
@@ -30,3 +34,44 @@ pub mod message;
...
+#[derive(Debug)]
+pub enum Error {
+    /// And I/O error
+    Io(io::Error),
+    /// Socket mutex was poisoned
+    SocketMutexPoisoned,
+    /// Not connected to peer
+    SocketNotConnectedToPeer,
+    /// Error propagated from subsystem
+    Detail(String, Box<Error>),
```
Comment (apoelstra) [inline src/network/mod.rs]: Variant can be dropped (see comments on network/listener.rs which is the only place this was used)

File: src/network/listener.rs [hunk 2]
```diff
@@ -40,7 +40,7 @@ pub trait Listener {
         // Open socket
         let mut ret_sock = Socket::new(self.network());
         if let Err(e) = ret_sock.connect(self.peer(), self.port()) {
-            return Err(util::Error::Detail("listener".to_owned(), Box::new(e)));
+            return Err(util::Error::Network(network::Error::Detail("listener".to_owned(), Box::new(e))));
         }
```
Comment (apoelstra) [inline src/network/listener.rs]: This whole `if` should be replaced by `ret_sock.connect(self.peer(), self.port())?;` because `ret_sock.connect` already returns a `network::Error`.

Then you can drop the new `self` import at the top of this file.

File: src/network/serialize.rs [hunk 3]
```diff
@@ -19,13 +19,100 @@
...
+    /// Error from the `byteorder` crate
+    ByteOrder(io::Error),
+    /// Network magic was not what we expected
+    BadNetworkMagic(u32, u32),
+    /// Network message was unrecognized
+    BadNetworkMessage(String),
+    /// Parsing error
+    ParseFailed,
+    /// Error propagated from subsystem
+    Detail(String, Box<Error>),
```
Comment (apoelstra) [inline src/network/serialize.rs]: We should drop the `Box<Error>` from this; the only thing ever packaged in it is `Error::ParseFailed`. In fact I think we should just make `ParseFailed` take a `String`.

File: src/network/serialize.rs [hunk 4]
```diff
@@ -19,13 +19,100 @@
...
+    /// Unsupported witness version
+    UnsupportedWitnessVersion(u8),
+}
+
+impl fmt::Display for Error {
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        match *self {
+            Error::Io(ref e) => fmt::Display::fmt(e, f),
+            Error::Detail(ref s, ref e) => write!(f, "{}: {}", s, e),
```
Comment (apoelstra) [inline src/network/serialize.rs]: I think every variant (once we merge `Detail` into `ParseFailed`) should do something here, and drop the `ref x` match.

File: src/network/serialize.rs (hunk 3 above)
Comment (apoelstra) [reply src/network/serialize.rs]: In fact it should take a `&'static str` rather than a `String`. The only place we dynamically generate a string is in `util::hex_bytes`, which (a) is only used in unit tests, (b) will be replaced alongside the hashes in the medium-term future.

File: src/network/message.rs [hunk 5]
```diff
@@ -174,30 +174,30 @@ impl<S: SimpleEncoder> ConsensusEncodable<S> for RawNetworkMessage {
 
 // TODO: restriction on D::Error is so that `propagate_err` will work;
 //       is there a more generic way to handle this?
```
Comment (apoelstra) [inline src/network/message.rs]: This TODO comment should be deleted.

File: src/util/mod.rs [hunk 6]
```diff
@@ -60,49 +62,23 @@ pub trait BitArray {
...
         match *self {
-            Error::Io(ref e) => fmt::Display::fmt(e, f),
-            Error::Base58(ref e) => fmt::Display::fmt(e, f),
-            Error::Bech32(ref e) => fmt::Display::fmt(e, f),
-            Error::ByteOrder(ref e) => fmt::Display::fmt(e, f),
-            Error::BadNetworkMagic(exp, got) => write!(f, "expected network magic 0x{:x}, got 0x{:x}", exp, got),
-            Error::BadNetworkMessage(ref got) => write!(f, "incorrect network message {}", got),
-            Error::Detail(ref s, ref e) => write!(f, "{}: {}", s, e),
             Error::Secp256k1(ref e) => fmt::Display::fmt(e, f),
+            Error::Serialize(ref e) => fmt::Display::fmt(e, f),
```
Comment (apoelstra) [inline src/util/mod.rs]: Should add case for `Error::Network`... and might as well replace `ref x` in the catchall case with `Error::SpvBadTarget | Error::SpvBadProofofWork` since there are only the two cases and it'll trigger exhaustiveness checking if we add new ones.

File: src/util/mod.rs [hunk 7]
```diff
@@ -111,60 +87,40 @@ impl fmt::Display for Error {
...
     fn cause(&self) -> Option<&error::Error> {
         match *self {
-            Error::Io(ref e) => Some(e),
-            Error::Base58(ref e) => Some(e),
-            Error::Bech32(ref e) => Some(e),
-            Error::ByteOrder(ref e) => Some(e),
-            Error::Detail(_, ref e) => Some(e),
             Error::Secp256k1(ref e) => Some(e),
+            Error::Serialize(ref e) => Some(e),
             _ => None
```
Comment (apoelstra) [inline src/util/mod.rs]: Ditto here.

File: src/network/serialize.rs (hunk 3 above)
Comment (dongcarl) [reply src/network/serialize.rs]: I believe that the `error(&mut self, err: String) -> Error` method of `RawDecoder`s also use a dynamic `String`, I do believe however, that with this overall change, we can eliminate that method and directly return `serialize::Error`s, does that sound good?

**Comment by dongcarl** [comment]
@apoelstra Is there any reason we're not using `e.fmt(f)` in `fmt::Display` impls?

**Comment by apoelstra** [comment]
@dongcarl I assumed that wouldn't work unless `fmt::Display` was imported, and I prefer to use the full path `fmt::Display` everywhere rather than doing so.

File: src/network/serialize.rs (hunk 3 above)
Comment (dongcarl) [reply src/network/serialize.rs]: @apoelstra I have replaced those instanced with their own `serialize::Error` vairants... What do we do with the `util::hex_bytes` case? Do I do the same?

**Comment by dongcarl** [comment]
All concerns should have been addressed.
