### PR TITLE
Fix PSBT key deserialisation byte size

### LINKED ISSUE #5622: PSBT raw key deserialization is buggy
In #2906 we changed the `type_value` from a `u8` to a `u64`. During this I missed that there is a calculation based on the encoding being a single byte, which now that its a compact int can be multiple bytes.

This `key_byte_size` calculation is buggy:

```rust
impl Key {
    pub(crate) fn decode<R: BufRead + ?Sized>(r: &mut R) -> Result<Self, Error> {
        let byte_size = r.read_compact_size()?;

        if byte_size == 0 {
            return Err(Error::NoMorePairs);
        }

        let key_byte_size: u64 = byte_size - 1;

        if key_byte_size > MAX_VEC_SIZE.to_u64() {
            return Err(encode::Error::OversizedVectorAllocation {
                requested: key_byte_size as usize,
                max: MAX_VEC_SIZE,
            }
            .into());
        }

        let type_value = r.read_compact_size()?;

        let mut key_data = Vec::with_capacity(key_byte_size as usize);
        for _ in 0..key_byte_size {
            key_data.push(Decodable::consensus_decode(r)?);
        }

        Ok(Key { type_value, key_data })
    }
}
```

### PR DESCRIPTION
**Pull request by mpbagot**
The PSBT Key decoding makes an assumption that the key type will always encode in a single byte in it's compact form. While this is sometimes true, it is not correct according to the spec and may fail in cases where key type values are large.

Fix the encode and decode implementations on Key to correctly calculate the type value size to add to the key length size.

Closes #5622

### CODE REVIEW

File: bitcoin/src/psbt/raw.rs [hunk 1]
```diff
@@ -68,25 +67,28 @@ impl fmt::Display for Key {
 
 impl Key {
     pub(crate) fn decode<R: BufRead + ?Sized>(r: &mut R) -> Result<Self, Error> {
-        let byte_size = r.read_compact_size()?;
+        let byte_size = r.read_compact_size()? as usize;
```
Comment (tcharding) [inline bitcoin/src/psbt/raw.rs]: I think this should use `try_from` and error if trying to decode a bytes slice that does not fit in memory. (Instead of silently truncating the length with the cast.)

In general we almost never want to cast in this repo, and if we do it has to have a code comment justifying it.

File: bitcoin/src/psbt/raw.rs [hunk 2]
```diff
@@ -68,25 +67,28 @@ impl fmt::Display for Key {
...
         if byte_size == 0 {
             return Err(Error::NoMorePairs);
         }
 
-        let key_byte_size: u64 = byte_size - 1;
+        // byte_size is the length of key_data + the length of type_value encoding
+        let type_value = r.read_compact_size()?;
+        let type_size = encoding::CompactSizeEncoder::encoded_size(
+            type_value.try_into().unwrap_or(usize::MAX)
+        );
```
Comment (tcharding) [inline bitcoin/src/psbt/raw.rs]: This limit is not in line with the BIP I believe. The type value can be any `u64` so we cannot convert it to `usize::MAX` on 32-bit machines.

**Comment by tcharding** [comment]
Just an FYI, I noticed while reviewing (and then reading the BIP) that we have to be careful not to break this:

 > If the signer encounters key-value pairs that it does not understand, it must pass those key-value pairs through when re-serializing the transaction.

ref: https://en.bitcoin.it/wiki/BIP_0174

File: bitcoin/src/psbt/raw.rs (hunk 2 above)
Comment (mpbagot) [reply bitcoin/src/psbt/raw.rs]: We're in a sticky situation then. The internals compact_size module is gone, and this version only takes a usize. Is introducing the logic inline acceptable?

Comment (tcharding) [reply bitcoin/src/psbt/raw.rs]: Bother. Yes I think inline it. With a comment saying something like 'the protocol abuses a compact size here to encode a value that is never used is relation to memory so conversion to a `usize` cannot be done'.

**Review by tcharding — APPROVED** [review]
ACK 652292780c044d157eb11d07a9fa515a8696ddc3

**Review by apoelstra — APPROVED** [review]
ACK 652292780c044d157eb11d07a9fa515a8696ddc3; successfully ran local tests
