### PR TITLE
transaction: make 0-input de/serialization always use Segwit 

### LINKED ISSUE #104: deserialize for Transaction Err if there are no transaction inputs
Hi!

Took me some time to understand why I had the issue. I have not yet investigated in rust-bitcoin code to understand the issue/propose a fix yet.

Raw transactions which do not include inputs are not properly handled.
This test fails on latest rust-bitcoin/master
```rust
#[test]
fn test_transaction_no_vin() {
    let hex_tx = hex_bytes("02000000000100ca9a3b00000000160014716f8e8fa281cb42bb6900ce35b73a13fa3e66e000000000").unwrap();
    let tx: Result<Transaction, _> = deserialize(&hex_tx);
    assert!(tx.is_ok());
}
```
If you replace the `assert` with `tx.unwrap()` you would get the following stack:

```
thread 'blockdata::transaction::tests::test_transaction_no_vin' panicked at 'called `Result::unwrap()` on an `Err` value: ByteOrder(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") })', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: bitcoin::blockdata::transaction::tests::test_transaction_no_vin
             at src/blockdata/transaction.rs:934
  11: bitcoin::__test::TESTS::{{closure}}
             at src/blockdata/transaction.rs:931
  12: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
test blockdata::transaction::tests::test_transaction_no_vin ... FAILED
```

Please note that bitcoind is able to decode the said transaction:
**Request**
```json
{
    "jsonrpc": "1.0", 
    "id":"curltest", 
    "method": "decoderawtransaction", 
    "params": 
["02000000000100ca9a3b00000000160014716f8e8fa281cb42bb6900ce35b73a13fa3e66e000000000"
    ]
    
}
```
**Response**
```json
{
    "result": {
        "txid": "e8069d1704d4d194f3fd6c85081851a8bc093a9f03da1be75065b961ddee1572",
        "hash": "e8069d1704d4d194f3fd6c85081851a8bc093a9f03da1be75065b961ddee1572",
        "version": 2,
        "size": 41,
        "vsize": 41,
        "locktime": 0,
        "vin": [],
        "vout": [
            {
                "value": 10,
                "n": 0,
                "scriptPubKey": {
                    "asm": "0 716f8e8fa281cb42bb6900ce35b73a13fa3e66e0",
                    "hex": "0014716f8e8fa281cb42bb6900ce35b73a13fa3e66e0",
                    "reqSigs": 1,
                    "type": "witness_v0_keyhash",
                    "addresses": [
                        "tb1qw9hcarazs8959wmfqr8rtde6z0aruehqt6m3m7"
                    ]
                }
            }
        ]
    },
    "error": null,
    "id": "curltest"
}
```

Looking at `struct Transaction` it does not look like input **must** be present so at this stage I am thinking about a bug in the `deserialize` function.

2 proposed way forward:
1. Support transaction without inputs
2. Improve the failure message to make it easier to debug

Let me know how you would prefer to move forward and I may be able to look into a patch.

### PR DESCRIPTION
**Pull request by apoelstra**
Builds on #151 

Fixes #104

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Needs rebase now.

**Comment by apoelstra** [comment]
Hmm. Transactions won't round-trip without #153 ... I guess I have to move the fuzzer commit to that PR.

**Comment by dongcarl** [comment]
Fuzzing seems to have failed?

**Comment by apoelstra** [comment]
cc @TheBlueMatt 

I added a commit which fixes the fuzz testing .. the issue is that if no-input transactions are always serialized with the segwit flag bytes, and the tx weight is computed as "length + 3*[length with witnesses stripped]", the segwit flag bytes get counted as non-witness bytes. Even though they *are* witness bytes for transactions with inputs.

I fixed `get_weight` to do this, but maybe it's the wrong fix?

**Comment by apoelstra** [comment]
Rebased.

File: src/blockdata/transaction.rs [hunk 1]
```diff
@@ -128,7 +128,18 @@ impl Default for TxOut {
     }
 }
 
-/// A Bitcoin transaction, which describes an authenticated movement of coins
+/// A Bitcoin transaction, which describes an authenticated movement of coins.
+///
+/// If any inputs have nonempty witnesses, the entire transaction is serialized
+/// in the post-BIP141 Segwit format which includes a list of witnesses. If all
+/// inputs have empty witnesses, the transaction is serialized in the pre-BIP143
```
Comment (stevenroose) [inline src/blockdata/transaction.rs]: You use BIP143 here instead of 141. 143 is not about encoding.

Comment (apoelstra) [reply src/blockdata/transaction.rs]: I always do that :). fixed.

**Comment by apoelstra** [comment]
We had a special-case for 0-input 0-output transactions that I think should be removed in this PR. I've done this, and updated the transaction fuzzer to check that every transaction roundtrips.

cc @TheBlueMatt github inexplicably is still saying you "approved" this code and I can't figure out how to undo it, even though I've substantially changed the content of the PR.

**Comment by stevenroose** [comment]
IIRC there is a setting in github where you can make approvals go away with
any new code change.

File: fuzz/fuzz_targets/deserialize_transaction.rs [hunk 2]
```diff
@@ -58,7 +60,7 @@ mod tests {
     #[test]
     fn duplicate_crash() {
         let mut a = Vec::new();
-        extend_vec_from_hex("00", &mut a);
+        extend_vec_from_hex("04000000000000000000", &mut a);
```
Comment (TheBlueMatt) [inline fuzz/fuzz_targets/deserialize_transaction.rs]: I thought we weren't leaving this in upstream code.

File: src/blockdata/transaction.rs [hunk 3]
```diff
@@ -279,7 +290,16 @@ impl Transaction {
...
         4;
         if inputs_with_witnesses == 0 {
-            non_input_size * 4 + input_weight
+            if self.input.is_empty() {
+                // If there are no inputs, then the transaction is serialized identically
+                // even after stripping witnesses (that is, even the segwit flag bytes are
+                // still there). Using the "length + 3 * stripped_length" formula, this
+                // means that the segwit flag bytes are considered to be non-witness bytes,
+                // and therefore have weight 8.
+                non_input_size * 4 + 8
```
Comment (TheBlueMatt) [inline src/blockdata/transaction.rs]: We're just gonna have to check this out in the fuzz test, it doesn't make sense to make get_weight not return the consensus-weight (which this isnt).

File: fuzz/fuzz_targets/deserialize_transaction.rs (hunk 2 above)
Comment (apoelstra) [reply fuzz/fuzz_targets/deserialize_transaction.rs]: Oops, I did not mean to check in an edit to the test.

File: src/blockdata/transaction.rs (hunk 3 above)
Comment (apoelstra) [reply src/blockdata/transaction.rs]: Kk. My thinking was that there isn't really a "consensus weight" for an invalid transaction anyway.

Comment (TheBlueMatt) [reply src/blockdata/transaction.rs]: Hmm, thats a valid point, though I'd kinda prefer to at least get the same weight that Bitcoin Core will tell you a bogus transaction like this has, even if our serialization is different to avoid ambiguity (though, last I checked, our serialization would deserialize on Bitcoin Core RPC functions).

Comment (apoelstra) [reply src/blockdata/transaction.rs]: Ok. I've fixed it, am fuzzing locally and will push when it finishes.

**Comment by apoelstra** [comment]
Thanks! Might be time to release 0.15 anyway since #156 did a major API overhaul.
