### PR TITLE
p2p: Fix Unknown NetworkMessage encoding

### LINKED ISSUE #4413: [Question]: Should it be possible to send non-standard messages using `NetworkMesage`?
The `NetworkData` enum has an "Unknown" variant, that is a catch-all for undefined messages. I was trying to use it to experiment with new `utreexo` messages, and I figured it is not possible to use it to craft new messages.

The reason is because this variant takes a `Vec<u8>` as payload, I've assumed this should be whatever payload you want to send serialized. But when creating a `RawNetworkMessage` and serializing it, [`NetworkMessage`'s `consensus_encode` calls `consensus_encode` for a `Vec<u8>`](https://github.com/rust-bitcoin/rust-bitcoin/blob/a9ddac178d937dce434ff4f9e8831055983a379e/bitcoin/src/p2p/message.rs#L417). This causes the original payload to be pre-pended with the size of that payload (because it is serialized as a slice of `u8`'s) but this corrupts the final result.

Here's an example code of how to recreate it

```rust
use std::str::FromStr;

use bitcoin::{
    consensus::encode::serialize_hex,
    hashes::Hash,
    p2p::message::{CommandString, NetworkMessage, RawNetworkMessage},
    BlockHash, Network,
};

fn main() {
    let block_hash =
        BlockHash::from_str("00000000000000000000b4d0f3c5e8a2f1c7e8a2f1c7e8a2f1c7e8a2f1c7e8a2")
            .unwrap();

    let message = NetworkMessage::Unknown {
        command: CommandString::try_from_static("geturoot").unwrap(),
        payload: block_hash.to_raw_hash().to_byte_array().to_vec(),
    };

    let raw_message = RawNetworkMessage::new(Network::Bitcoin.magic(), message);

    println!("{}", serialize_hex(&raw_message));
}
```
It will output:

`f9beb4d967657475726f6f74000000002100000098538b6a-->20<--a2e8c7f1a2e8c7f1a2e8c7f1a2e8c7f1a2e8c5f3d0b400000000000000000000`
I've marked the byte that shouldn't be there, it is a size for the byte-array the follows. Notice how the payload size is `0x21` (33). This message should be 32 bytes long (exactly one block hash).

I'm not calling this a bug, because I don't know if this is intended to be used that way. I'm leaving it as a question to whether this should be something possible or not.

### PR DESCRIPTION
**Pull request by mpbagot**
The NetworkMessageEncoder and old Encodable implementation for NetworkMessage make use of the Vec\<u8\> encoding for the raw payload data. This introduces a vector length prefix to the start of the encoding which causes the roundtrip for Unknown NetworkMessage types to fail. In practice, NetworkMessage will only ever be decoded through the RawNetworkMessage, where a payload length will be known. As such, this length prefix is not necessary in the encoding and can be trivially removed.

Change Unknown NetworkMessage encoding to directly write the vector of bytes instead of using Vec\<u8\> encoding logic.

Closes #4413 and #5659

### CODE REVIEW

File: p2p/src/message.rs [hunk 1]
```diff
@@ -797,7 +797,7 @@ impl Encodable for NetworkMessage {
             | Self::WtxidRelay
             | Self::FilterClear
             | Self::SendAddrV2 => Ok(0),
-            Self::Unknown { payload: ref data, .. } => data.consensus_encode(writer),
+            Self::Unknown { payload: ref data, .. } => writer.write(data),
```
Comment (tcharding) [inline p2p/src/message.rs:800]:
```suggestion
            // Don't use consensus_encode so as not to add a length suffix.
            Self::Unknown { payload: ref data, .. } => writer.write(data),
```

**Review by tcharding — DISMISSED** [review]
ACK 5805a09f3678c8f6bc2a2cef58eacea027261b2a

**Comment by tcharding** [comment]
I acked but I'd like to see the comment added because its surprising to see a bunch of `consenus_encode` calls then a `write` call and its not immediately obvious why. 

(For some reason I've been totally brain dead trying to review this over the last few days ...)

**Comment by tcharding** [comment]
Thanks mate, I'm appreciating your dev process. You are turning out to be super easy to work with, nice one well done.

**Comment by rustaceanrob** [comment]
ACK cf1a9fee8ee9fdcac2fdd1d85d243ee46b32eb84
