### PR TITLE
Fix decoder and encoder re-exports in `bitcoin`

### LINKED ISSUE #5689: Investigate why `bitcoin::block::HeaderDecoderError` does not exist
For all `primitives::Foo` there must be a `bitcoin::Foo` and we have tooling that is supposed to check this (or did I only do it for `primitives`?)

I was surprised to find that `bitcoin::block::HeaderDecoderError` does not exist. Fix it and investigate how this happened incase there are other missing types.

Downstream testing for the win.

### PR DESCRIPTION
**Pull request by mpbagot**
The bitcoin crate should always be a superset of primitives, and primitives a superset of units. Due to a filter check in generate-bitcoin-re-export-test.sh, encoder and decoder types and their associated errors are not being caught missing from bitcoin.

Remove the encoder/decoder type filter from generate-bitcoin-re-export-test.sh and correctly re-export all required types.

Closes #5689

### CODE REVIEW

File: bitcoin/src/blockdata/script/mod.rs [hunk 1]
```diff
@@ -81,10 +81,13 @@ pub use self::{
...
-    ScriptHash, ScriptHashableTag, ScriptPubKey, ScriptPubKeyBuf, ScriptPubKeyTag, ScriptSig,
-    ScriptSigBuf, ScriptSigTag, Tag, TapScript, TapScriptBuf, TapScriptTag, WScriptHash,
-    WitnessScript, WitnessScriptBuf, WitnessScriptSizeError, WitnessScriptTag,
+    ScriptBufDecoder, ScriptEncoder, ScriptHash, ScriptHashableTag, ScriptPubKey,
+    ScriptPubKeyBuf, ScriptPubKeyTag, ScriptSig, ScriptSigBuf, ScriptSigTag, Tag, TapScript,
+    TapScriptBuf, TapScriptTag, WScriptHash, WitnessScript, WitnessScriptBuf,
+    WitnessScriptSizeError, WitnessScriptTag,
 };
+#[doc(no_inline)]
+pub use primitives::script::{ScriptBufDecoderError};
```
Comment (tcharding) [inline bitcoin/src/blockdata/script/mod.rs]:
```suggestion
pub use primitives::script::ScriptBufDecoderError;
```

File: bitcoin/src/blockdata/transaction.rs [hunk 2]
```diff
@@ -33,10 +33,17 @@ use crate::{internal_macros, Amount, FeeRate, Sequence, SignedAmount};
...
+    TransactionDecoderError, TxInDecoderError, TxMerkleNodeDecoderError, TxOutDecoderError,
+    VersionDecoderError,
+};
 #[doc(inline)]
 pub use primitives::transaction::{
-    Ntxid, OutPoint, Transaction, TxIn, TxOut, Txid, Version, Wtxid,
+    BlockHashDecoder, Ntxid, OutPoint, OutPointDecoder, OutPointEncoder, Transaction,
+    TransactionDecoder, TransactionEncoder, TxIn, TxInDecoder, TxInEncoder,
+    TxMerkleNodeDecoder, TxOut, TxOutDecoder, TxOutEncoder, Txid, Version,
+    VersionDecoder, VersionEncoder, WitnessesEncoder, Wtxid,
```
Comment (tcharding) [inline bitcoin/src/blockdata/transaction.rs:46]: In a follow up it would be nice to be uniform in the placement of these blocks. I'd say first the `inline` block and then the `no_inline` block

File: bitcoin/src/merkle_tree/mod.rs [hunk 3]
```diff
@@ -19,6 +19,8 @@ use io::{BufRead, Write};
 #[rustfmt::skip]
 #[doc(inline)]
 pub use primitives::{TxMerkleNode, WitnessMerkleNode};
+#[doc(inline)]
+pub use primitives::merkle_tree::TxMerkleNodeEncoder;
```
Comment (tcharding) [inline bitcoin/src/merkle_tree/mod.rs]: Why no decoder and decoder error? And why did the script not find that?

Comment (tcharding) [reply bitcoin/src/merkle_tree/mod.rs]: Is it because of the unusual `hash_types` module? And if so is that module byting us in other places too?

**Comment by tcharding** [comment]
Stoked to see this PR. The encoder/decoder re-exports have been nagging at me for ages now.

**Comment by tcharding** [comment]
Just FTR did you check `units` too? But it looks like `generate-primitives-re-export-test.sh` does not suffer this bug.

File: bitcoin/src/merkle_tree/mod.rs (hunk 3 above)
Comment (mpbagot) [reply bitcoin/src/merkle_tree/mod.rs]: The `TxMerkleNodeDecoder` is exported from `transaction` in `primitives`, while the encoder is exported from `merkle_tree`. If it's wrong, we should fix it in `primitives`.
`hash_types` is not directly public, so things in it are re-exported from other modules in `primitives`.

**Comment by mpbagot** [comment]
> Just FTR did you check units too? But it looks like generate-primitives-re-export-test.sh does not suffer this bug.

I did not. I looked over the script and it didn't appear to have the problem so I didn't delve any further into it. I'll take a look, but I'm fairly certain that it's fine.

Edit: This made me notice that the script ignores `pub use` re-exports in `primitives`. For example, `Amount` is a re-export from `units`. It is ignored by the bitcoin re-export script because it's not defined in `primitives`, just re-exported.

File: bitcoin/src/merkle_tree/mod.rs (hunk 3 above)
Comment (tcharding) [reply bitcoin/src/merkle_tree/mod.rs]: Yes looks to me like this is wrong, both should IMO be re-exported from `merkle_tree`.

Comment (tcharding) [reply bitcoin/src/merkle_tree/mod.rs]: The `BlockHash` encoder/decoder are probably in the wrong place too. Perhaps better to re-export from `block` than from `transaction`.

Comment (mpbagot) [reply bitcoin/src/merkle_tree/mod.rs]: `BlockHash` encoder/decoder are exported from `block`. They're just also exported from `transaction`. Should it be only `block`?

Comment (tcharding) [reply bitcoin/src/merkle_tree/mod.rs]: I believe so.

**Review by apoelstra — APPROVED** [review]
ACK 18ad13e3c8bc9a2a04bca81bd721faf55c920357; successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK 18ad13e3c8bc9a2a04bca81bd721faf55c920357

**Comment by apoelstra** [comment]
Needs rebase.
