### PR TITLE
Fix serde struct macros deserialization impls

### LINKED ISSUE #374: Serializing then deserializing an OutPoint fails
This is easy to reproduce:

```rust
use bitcoin::hashes::{sha256d, Hash};
use bitcoin::OutPoint;

fn main() {
    let out_point = OutPoint {
        txid: sha256d::Hash::hash(&"foobar"[..]),
        vout: 0,
    };
    let serialized = bincode::serialize(&out_point).unwrap();

    // This line panics.
    let _deserialized: OutPoint = bincode::deserialize(&serialized).unwrap();
}
```

The error message is "invalid type: sequence, expected a struct"

### PR DESCRIPTION
**Pull request by canndrew**
Fixes #374 

The `Deserialize` impls generated by `serde_struct_impl` and `serde_struct_human_string_impl` need to be able to handle serialization formats which serialize structs as sequences (such as bincode).

This PR adds `visit_seq` methods to the `Visitor` types defined by these macros, in addition to the existing `visit_map` methods. The implementation is taken directly from the serde docs: https://serde.rs/deserialize-struct.html

### CODE REVIEW

File: src/internal_macros.rs [hunk 1]
```diff
@@ -282,6 +282,28 @@ macro_rules! serde_struct_impl {
...
+                        use $crate::serde::de::Error;
+
+                        let length = 0;
+                        $(
+                            let $fe = seq.next_element()?.ok_or_else(|| {
+                                Error::invalid_length(length, &self)
+                            })?;
+                            #[allow(unused_variables)]
+                            let length = length + 1;
+                        )*
```
Comment (elichai) [inline src/internal_macros.rs]: Did you look at the expanded output? I'm not sure if the length is preserved the way you'd want it.
could you replace it with a mutable length that you add 1 to?

**Comment by dr-orlovsky** [comment]
Can you pls also add unit tests with serialization/deserialization for the structs which use `serde_struct_impl`?

File: src/internal_macros.rs (hunk 1 above)
Comment (canndrew) [reply src/internal_macros.rs]: This works fine the way it is. It's the way I usually write these sorts of macros. I can change it if you want though.

**Comment by canndrew** [comment]
@dr-orlovsky I've extended the `serde_round_trip!` macro to use to do a round trip with bincode as well as json. Is that sufficient?

**Comment by apoelstra** [comment]
Please, no more deps, even for tests.

For serialization we're pretty-much limited to a "best effort" set of tests, since it seems that every de/serialization format has its own quirks regarding round-tripping, and not even `serde_test` can capture this. Given that, rather than trying to scattershot various serialization crates it's better to just stick with what we have.

I was ok with the original set of tests.

**Comment by elichai** [comment]
As @apoelstra said, 
if you can't get `serde_test` to test this usecase then fix `serde_test` :)
I really want to get rid of these manual implementations 
is there any reason not to do that other than #317? (that's a great reason, just trying to understand our options)

File: src/internal_macros.rs (hunk 1 above)
Comment (stevenroose) [reply src/internal_macros.rs]: It looks like it'd work, but it seems like a naive compiler would recreate the length variable at the top of the stack every time instead of just incrementing. Why can't you just drop the `let`? `length += 1;` should do even.

**Comment by apoelstra** [comment]
Yes, we tried to remove them then almost immediately got nailed by 317.

**Comment by elichai** [comment]
:(
Maybe use some `cargo expand` magic to generate on stable and compare in the CI :(
(that way these problems shouldn't happen anymore but it sucks.)

**Comment by canndrew** [comment]
I've updated the PR to remove bincode as a dependency and from `serde_round_trip!`. Is it possible to get this merged as-is, given that it fixes a bug and I know that the new code at least works for my own code?

**Comment by canndrew** [comment]
Btw, what's the rationale for not wanting to introduce new dependencies for tests? I understand dependencies are a security concern (which is obviously pretty important for this crate) but surely that doesn't apply for tests, right?

File: src/internal_macros.rs (hunk 1 above)
Comment (canndrew) [reply src/internal_macros.rs]: Do we really need to worry about compiler bugs producing incorrect code?

I tried changing it anyway, since it's not worth arguing about, but then you can't add the `#[allow(unused_assignment)]` attribute to the line because rust complains that "attributes on expressions are experimental", and without that you get compiler warnings about the last incrementation of `length` being unused.

**Comment by elichai** [comment]
> Btw, what's the rationale for not wanting to introduce new dependencies for tests? I understand dependencies are a security concern (which is obviously pretty important for this crate) but surely that doesn't apply for tests, right?

The main one I see is that they tend to break our backwards compatibility (ie can't run tests to the targeted rust 1.22)

**Comment by knocte** [comment]
> I've updated the PR

ping reviewers :)

**Comment by knocte** [comment]
@stevenroose | @elichai ping?

**Comment by knocte** [comment]
is this blocked on something?
