### PR TITLE
Check that the amount precision isn't more than the size of the amount

### LINKED ISSUE #300: Amount parsing can crash
Putting `"30206d736174"` (ascii `0 msat`) into the `deserialize_amount` causes a signed underflow crash

### LINKED ISSUE #311: Fuzz test found a problem in Amount
looks like the fuzzer found the test data "2d30206d736174" which from_utf8_lossy is "-0 msat" which is crashing the SignedAmount::from_str(&data_str)

### PR DESCRIPTION
**Pull request by elichai**
This should fix #300
Basically if the precision is longer than the length of the number than it's too precise.

This should also solve another unwanted behavior I thought of, 
which is:
if `last_n==s.len()`.
then `s` will be `""`. 
which will make this loop: `for c in s.chars()` to never run(chars is size 0).
`decimals` will be unwrapped to 0, `max_decimals` is also 0.
so `scale_factor` is now zero (`let scale_factor = max_decimals - decimals.unwrap_or(0);`)
so `for _ in 0..scale_factor` won't run either.

which means the function will return with the default value of `value`(0)

Edit: Fixes #311 too

### CODE REVIEW

File: src/util/amount.rs [hunk 1]
```diff
@@ -160,7 +160,7 @@ fn parse_signed_to_satoshi(
             // there are no decimals and the last digits are zeroes as
             // many as the difference in precision.
             let last_n = precision_diff.abs() as usize;
-            if s.contains(".") || s.chars().rev().take(last_n).any(|d| d != '0') {
+            if s.contains(".") || last_n >= s.len() || s.chars().rev().take(last_n).any(|d| d != '0') {
```
Comment (dpc) [inline src/util/amount.rs]: I would make this `bool is_too_precise(&str)`. Then it is self-explanatory, and you can add couple of doctests and stuff.

**Comment by dpc** [comment]
Seems OK to me, but I have little experience with dealing this atrocious idea of using floats for balances. I'm surprised this isn't already phased out.

**Comment by elichai** [comment]
Travis is failing for unrelated errors.

**Comment by apoelstra** [comment]
@dpc this floating point code is new actually. It can't be phased out because serde-json has no other way to support non-integer numbers such as the ones that Bitcoin Core's RPC outputs.

**Comment by dpc** [comment]
@apoelstra I meant in Bitcoin Core. My understanding why float number conversions are needed in Bitcoin libraries is because Bitcoin Core uses them for balances in the API, and the reason for that is (maybe) because JS/JSON by default has precision problems in big integers. If you ask me, Bitcoin Core should just start returning integers in satoshis (maybe stringified, if the precision is a problem), side by side old float number balances, deprecate the old ones, and target their removal in some future version.

**Comment by elichai** [comment]
@dpc I don't know a lot about the history of the json api but this sounds like a conversation for an issue on bitcoin/bitcoin github

**Comment by apoelstra** [comment]
@dpc Bitcoin Core is not going to break nearly every wallet-centric RPC for the sake of precision errors in json libraries, which should not be an issue anyway since `f64` has enough precision to uniquely specify (by rounding, if necessary) every number from 0 to 21 million with 8 decimal digits.

**Comment by apoelstra** [comment]
Can you add a unit test for #311

File: src/util/amount.rs [hunk 2]
```diff
@@ -1208,6 +1213,15 @@ mod tests {
         assert_eq!(sp("-200000000000 BTC"), Err(E::TooBig));
         assert_eq!(p("18446744073709551616 sat"), Err(E::TooBig));
 
+        assert_eq!(sp("0 msat"), Err(E::TooPrecise));
+        assert_eq!(sp("-0 msat"), Err(E::TooPrecise));
+        assert_eq!(sp("000 msat"), Err(E::TooPrecise));
+        assert_eq!(sp("-000 msat"), Err(E::TooPrecise));
+        assert_eq!(p("0 msat"), Err(E::TooPrecise));
+        assert_eq!(p("-0 msat"), Err(E::TooPrecise));
```
Comment (elichai) [inline src/util/amount.rs]: Should this be `TooPrecise` or `Negative`?

**Comment by elichai** [comment]
Done

File: src/util/amount.rs [hunk 3]
```diff
@@ -129,6 +129,11 @@ impl error::Error for ParseAmountError {
     }
 }
 
+
+fn is_too_precise(s: &str, precision: usize) -> bool {
```
Comment (dongcarl) [inline src/util/amount.rs]: Please add a comment here describing this check

File: src/util/amount.rs (hunk 2 above)
Comment (stevenroose) [reply src/util/amount.rs]: Yeah I had this dilemma as well. I decided that if two things are wrong, it doesn't matter which one you report; so one should just return the first one that is detected. In this case the negative check is deferred until later, so it's faster to return the `TooPrecise` case.

File: src/util/amount.rs (hunk 3 above)
Comment (stevenroose) [reply src/util/amount.rs]: This could even be inlined again IMO, but if taken out as a method, please provide some docs for context. Implementation seems correct.

File: src/util/amount.rs (hunk 2 above)
Comment (stevenroose) [reply src/util/amount.rs]: To make the test more correct one could expect **either** a `Negative` or `TooPrecise` error, so that the tests don't break if the implementation would change the check order.

**Comment by stevenroose** [comment]
Thanks for fixing this!

File: src/util/amount.rs (hunk 2 above)
Comment (apoelstra) [reply src/util/amount.rs]: Nah, we can fix the test when/if it breaks. It's good to notice changed behavior like this anyway, in case users are depending on it.
