### PR TITLE
Test: add invalid segwit transaction test

### LINKED ISSUE #2183: Witness presence check not tested
[This condition](https://github.com/rust-bitcoin/rust-bitcoin/blob/966b190f238408e24efd768ffa2bcdb6046e0cea/bitcoin/src/blockdata/transaction.rs#L1100) appears untested. I've been doing some experiments which didn't perform the check and the tests did *not* fail.

### PR DESCRIPTION
**Pull request by startup-dreamer**
Tries to close #2183 

Added the test for invalid segwit transaction (witness flag is set but no witness is present) using [This suggested hex](https://github.com/rust-bitcoin/rust-bitcoin/issues/2183#issuecomment-1901207149) by Kixunil

### CODE REVIEW

File: bitcoin/src/blockdata/transaction.rs [hunk 1]
```diff
@@ -1638,6 +1638,17 @@ mod tests {
...
 
+    #[test]
+    fn segwit_invalid_transaction() {
+        let tx_bytes = hex!("0000fd000001021921212121212121212121f8b372b0239cc1dff600000000004f4f4f4f4f4f4f4f000000000000000000000000000000333732343133380d000000000000000000000000000000ff000000000009000dff000000000000000800000000000000000d");
+        let tx: Result<Transaction, _> = deserialize(&tx_bytes);
+        assert!(tx.is_err());
+        assert!(tx
+            .unwrap_err()
+            .to_string()
+            .contains("witness flag set but no witnesses present"));
```
Comment (Kixunil) [inline bitcoin/src/blockdata/transaction.rs:1649]: I'm not entirely happy about checking messages like this but I think it's acceptable. My upcoming PR will change it anyway. Also the assert above this was not needed since `unwrap_err` already does the same thing.

**Review by Kixunil — APPROVED** [review]
ACK fe8d559d6909e77603c1b8382098b1bb6945eb7b

**Review by apoelstra — APPROVED** [review]
ACK fe8d559d6909e77603c1b8382098b1bb6945eb7b
