### PR TITLE
Address validity invariant cleanups

### LINKED ISSUE #1561: Segwit Address struct allows constructing invalid Address
Both `Address::from_str` and `Address::from_script` check constraints witness programs (len between 2 and 40 and others). But it is possible to directly construct the `Address` struct as all its member fields (`Payload` in particular) are public. 

We should make internal fields of  `Address` private and a make failing constructor that checks the invariants.

### PR DESCRIPTION
**Pull request by sanket1729**
Fixes #1561. 

Highlights:

- Segwitv0 programs with lengths apart from 20 or 32 are invalid `Address` struct. Such Addresses are useless and we should not parse/create them.
- Renamed `is_standard` to `is_spend_standard`.

### CODE REVIEW

File: bitcoin/src/address.rs [hunk 1]
```diff
@@ -492,28 +518,30 @@ impl Payload {
...
+        Payload::WitnessProgram(prog)
     }
 
     /// Returns a byte slice of the payload
     pub fn as_bytes(&self) -> &[u8] {
         match self {
             Payload::ScriptHash(hash) => hash.as_ref(),
             Payload::PubkeyHash(hash) => hash.as_ref(),
-            Payload::WitnessProgram { program, .. } => program,
+            Payload::WitnessProgram(prog) => prog.program(),
```
Comment (sanket1729) [inline bitcoin/src/address.rs:544]: Unrelated: But this API is sketchy in how it is used. If anything I would expect the `witness_version` to get serialized in `as_bytes` method of the `PayLoad`. 

Should open an issue about it.

Comment (Kixunil) [reply bitcoin/src/address.rs:544]: Oh, I think I complained about this, IIRC this was introduced when implementing `is_related_to_pubkey`. The function shouldn't be `pub`.

File: bitcoin/src/blockdata/script.rs [hunk 2]
```diff
@@ -1122,28 +1122,44 @@ impl ScriptBuf {
...
+            .push_slice(witness_program.program())
+            .into_script()
+    }
+
+    /// Internal method to a witness scriptPubkey with a given version and program.
+    /// Does not do any checks on version or program.
+    ///
+    // Used internally by `new_v0_p2wpkh`, `new_v0_p2wsh`, `new_v1_p2tr`, and `new_v1_p2tr_tweaked`
+    // for convenience.
+    fn new_witness_program_unchecked(version: WitnessVersion, program: &[u8]) -> Self {
```
Comment (Kixunil) [inline bitcoin/src/blockdata/script.rs:1162]: Maybe add a `debug_assert!`?

File: bitcoin/src/address.rs [hunk 3]
```diff
@@ -848,10 +848,18 @@ impl Address {
 	self.address_type_internal()
     }
 
+    /// Checks whether or not the address is following Bitcoin standardness rules when
+    /// *spending* from this address.
+    ///
+    /// SegWit addresses with unassigned witness versions or non-standard program sizes are
+    /// considered non-standard.
+    pub fn is_spend_standard(&self) -> bool { self.address_type().is_some() }
```
Comment (Kixunil) [inline bitcoin/src/address.rs:885]: If I'm correct that receiver statically knows the address is standard then I think the method is useless and we should just remove it. If there is any use then I want a warning in doc that this should **not** be called by the sender.

**Review by Kixunil — CHANGES_REQUESTED** [review]
Looks good, I only want a reason to keep `is_spend_standard` and if yes, then better doc.

File: bitcoin/src/address.rs (hunk 3 above)
Comment (sanket1729) [reply bitcoin/src/address.rs:889]: > If I'm correct that receiver statically knows the address is standard

This method is preciously how the receiver would know that the address they are receiving the money to is standard.

Comment (Kixunil) [reply bitcoin/src/address.rs:889]: The receiver is the one who constructs the address so I would expect this to be handled by construction.

File: bitcoin/src/address.rs [hunk 4]
```diff
@@ -492,28 +519,31 @@ impl Payload {
...
+            WitnessVersion::V1,
+            output_key.to_inner().serialize().to_vec()
+        ).expect("taproot output key has len 32 <= 40");
+        Payload::WitnessProgram(prog)
     }
 
-    /// Returns a byte slice of the payload
-    pub fn as_bytes(&self) -> &[u8] {
+    /// Returns a byte slice of the inner program of the payload. Incase the payload
+    /// ia a script hash or pubkey hash, the a reference to the hash is returned.
```
Comment (Kixunil) [inline bitcoin/src/address.rs:541]: Nits: "is", "a reference"

File: bitcoin/src/address.rs [hunk 5]
```diff
@@ -725,15 +756,15 @@ impl<V: NetworkValidation> Address<V> {
...
+            Payload::WitnessProgram(ref prog) => {
                 // BIP-141 p2wpkh or p2wsh addresses.
-                match version {
-                    WitnessVersion::V0 => match prog.len() {
+                match prog.version() {
+                    WitnessVersion::V0 => match prog.program().len() {
                         20 => Some(AddressType::P2wpkh),
                         32 => Some(AddressType::P2wsh),
-                        _ => None,
+                        _ => None, // Technically unreachable, but we don't want to panic when not required.
```
Comment (Kixunil) [inline bitcoin/src/address.rs:765]: Silently ignoring bugs is not great either, `debug_assert` would be nice.

File: bitcoin/src/address.rs [hunk 6]
```diff
@@ -848,10 +879,20 @@ impl Address {
 	self.address_type_internal()
     }
 
+    /// Checks whether or not the address is following Bitcoin standardness rules when
+    /// *spending* from this address. This method should *NOT* called by senders. For forward
+    /// compatibility, the senders must send to any [`Address`]. Receivers can use this method to
+    /// check whether or not they can spend from this address.
```
Comment (Kixunil) [inline bitcoin/src/address.rs:885]: I like having a warning in summary but not sure if this long is appropriate. Maybe something like "Checks whether the address obeys Bitcoin standardness rules when *spending* from this address. **NOT* to be called by senders!" And full explanation in description. Anyway, I won't block the PR because of it.

**Review by Kixunil — APPROVED** [review]
ACK 30d251ee866405973fb9c433f247407b389fcf6e

File: bitcoin/src/address.rs (hunk 3 above)
Comment (sanket1729) [reply bitcoin/src/address.rs:889]: Are you suggesting two structures? `SendingAddress` and `RecievingAddress`. Or perhaps yet another phantom data type in Address itself. We want to support sending to unknown addresses, but don't want to receive it ourselves. I don't see how we can handle this under the current `Address` construction. 

That being said, I don't see any utility for wallet developers who want to use this method. It maybe useful enthusiasts who scan the blockchain for non-standard spends or for block explorers. I recall somebody did a taproot spend before taproot was activated to fork off UASF nodes.

File: bitcoin/src/address.rs (hunk 4 above)
Comment (tcharding) [inline bitcoin/src/address.rs:541]:
```suggestion
    /// Returns a byte slice of the inner program of the payload. If the payload
    /// is a script hash or pubkey hash, a reference to the hash is returned.
```

File: bitcoin/src/blockdata/script.rs [hunk 7]
```diff
@@ -1122,28 +1122,47 @@ impl ScriptBuf {
...
```
Comment (tcharding) [inline bitcoin/src/blockdata/script.rs:1162]:
```suggestion
    /// Generates P2WSH-type of scriptPubkey with a given [`WitnessVersion`] and the program bytes.
    ///
    /// Convenience method used by `new_v0_p2wpkh`, `new_v0_p2wsh`, `new_v1_p2tr`, and
    /// `new_v1_p2tr_tweaked`.
    fn new_witness_program_unchecked(version: WitnessVersion, program: &[u8]) -> Self {
```

File: bitcoin/src/blockdata/script.rs [hunk 8]
```diff
@@ -1122,28 +1122,47 @@ impl ScriptBuf {
...
     /// Generates P2TR for key spending path for a known [`TweakedPublicKey`].
     pub fn new_v1_p2tr_tweaked(output_key: TweakedPublicKey) -> Self {
-        ScriptBuf::new_witness_program(WitnessVersion::V1, &output_key.serialize())
+        // output key is 32 bytes long, so it's safe to use `new_witness_program_unchecked` (Segwitv1)
+        ScriptBuf::new_witness_program_unchecked(WitnessVersion::V1, &output_key.serialize())
     }
 
     /// Generates P2WSH-type of scriptPubkey with a given hash of the redeem script.
-    pub fn new_witness_program(version: WitnessVersion, program: &[u8]) -> Self {
+    pub fn new_witness_program(witness_program: &WitnessProgram) -> Self {
```
Comment (tcharding) [inline bitcoin/src/blockdata/script.rs:1150]:
```suggestion
    /// Generates P2WSH-type of scriptPubkey with a given [`WitnessProgram`].
    pub fn new_witness_program(witness_program: &WitnessProgram) -> Self {
```

**Review by tcharding — COMMENTED** [review]
Just a few rustdoc comment fixes.

File: bitcoin/src/address.rs (hunk 3 above)
Comment (Kixunil) [reply bitcoin/src/address.rs:889]: > Are you suggesting two structures?

Not really. If I write an application that uses some of the common ways of receiving then I write the code such that `Address` is always valid and don't need to check it. Would would I even do if it's wrong?

> That being said, I don't see any utility for wallet developers who want to use this method.

Yeah, I believe we both don't for the same reason.

> It maybe useful enthusiasts who scan the blockchain for non-standard spends or for block explorers.

Shouldn't the scripts be checked instead of addresses?

> I recall somebody did a taproot spend before taproot was activated to fork off UASF nodes.

OT but sounds like that person was confused? I don't see how it could fork off UASF nodes.

Comment (apoelstra) [reply bitcoin/src/address.rs:889]: >Not really. If I write an application that uses some of the common ways of receiving then I write the code such that Address is always valid and don't need to check it.

This is why it's a utility method and not something that we're gating constructors on or enforcing in the type system.

>Would would I even do if it's wrong?

Lol assert probably. But I think it's most common to hit cases like this during transition periods...like, maybe your wallet would let you generate a Taproot address before Taproot was active, but would put a bunch of warnings on it or otherwise try to prevent you from using it until it became standard.

>Shouldn't the scripts be checked instead of addresses?

This is an interesting thought. Maybe users who want to do this should need to first convert the address to a scriptpubkey, and then do a standardness check on that. But I think such an API change should wait for script tagging.

File: bitcoin/src/address.rs (hunk 5 above)
Comment (apoelstra) [reply bitcoin/src/address.rs:765]: Agreed. TBH I'd even prefer an unconditional `unreachable!` panic.

**Review by apoelstra — DISMISSED** [review]
ACK 30d251ee866405973fb9c433f247407b389fcf6e

**Comment by apoelstra** [comment]
@sanket1729 should I merge this or do you want to address @tcharding's nits?

**Comment by sanket1729** [comment]
@apoelstra, force-pushing in a few mins

File: bitcoin/src/blockdata/script.rs (hunk 7 above)
Comment (sanket1729) [reply bitcoin/src/blockdata/script.rs]: Addressed. But also added the  ` Does not do any checks on version or program` which I feel is relevant to the method.

**Comment by sanket1729** [comment]
Ready for review again.

File: bitcoin/src/address.rs (hunk 6 above)
Comment (sanket1729) [reply bitcoin/src/address.rs]: Changed

**Review by apoelstra — APPROVED** [review]
ACK 44d3ec487db8ab2724af12e07aafb2b42aa05c09

**Review by tcharding — APPROVED** [review]
ACK 44d3ec487db8ab2724af12e07aafb2b42aa05c09
