### PR TITLE
Fix TapTree hidden branches bug

### LINKED ISSUE #928: TapTree roundtrip serialization fails with hidden branches
`TapTree` can be build from `TaprootBuilder` having hidden branches; however PSBT does not provide format for presenting hidden branches. Thus, `TapTree` psbt serialization is buggy: it will present incorrect representation of trees/descriptors with hidden branches. As a result, `TapTree` also fails to roundtrip if a hidden branch is present:

```rust
    #[test]
    fn taptree_roundtrip_hidden() {
        let mut builder = compose_taproot_builder(0x51, [2, 2, 2]);
        builder = builder.add_leaf_with_ver(3, Script::from_hex("b9").unwrap(), LeafVersion::from_consensus(0xC2).unwrap()).unwrap();
        builder = builder.add_hidden(3, sha256::Hash::default()).unwrap();
        let tree = TapTree::from_inner(builder).unwrap();
        let tree_prime = TapTree::deserialize(&tree.serialize()).unwrap();
        assert_eq!(tree, tree_prime);
    }
```
fails: `test result: FAILED. 248 passed; 1 failed`

---- util::psbt::serialize::tests::taptree_roundtrip_hidden stdout ----
thread 'util::psbt::serialize::tests::taptree_roundtrip_hidden' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFailed("Tree not in DFS order")', src/util/psbt/serialize.rs:415:66

The proposed solution is to introduce `TaprootBuilder::has_hidden_branches` and check that in `TapTree::from_inner`, returning error. I am already working on a PR fixing that.

Related discussion: https://github.com/rust-bitcoin/rust-bitcoin/pull/924#issuecomment-1085387179

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Closes #928

### CODE REVIEW

File: src/util/psbt/map/output.rs [hunk 1]
```diff
@@ -106,11 +121,11 @@ impl TapTree {
     ///
     /// # Return
     /// A `TapTree` iff the `inner` builder is complete, otherwise return the inner as `Err`.
```
Comment (shesek) [inline src/util/psbt/map/output.rs:123]: The comment here was not updated to reflect the change

File: src/util/psbt/map/output.rs [hunk 2]
```diff
@@ -106,11 +121,11 @@ impl TapTree {
...
-    pub fn from_inner(inner: TaprootBuilder) -> Result<Self, TaprootBuilder> {
+    pub fn from_inner(inner: TaprootBuilder) -> Result<Self, IncompleteTapTree> {
```
Comment (sanket1729) [inline src/util/psbt/map/output.rs:124]: It is rust convention to return `inner` as `Err` when it is consumed. So, the caller at least gets the copy it needs. 

I don't remember completely, but I think @Kixunil suggested I do this in his review.

**Review by sanket1729 — COMMENTED** [review]
Did not do a detail review, but left one which we should discuss before we invest more time

File: src/util/psbt/map/output.rs (hunk 2 above)
Comment (dr-orlovsky) [reply src/util/psbt/map/output.rs:124]: Ah, ok. But it is really confusing when working with an API like that - I was confused byself, as you've seen in the issue

Comment (dr-orlovsky) [reply src/util/psbt/map/output.rs:124]: @sanket1729 what about making `IncompleteTapTree` type to be a wrapper around `TaprootBuilder`, implemeting `std::error::Error`?

File: src/util/psbt/map/output.rs (hunk 1 above)
Comment (dr-orlovsky) [reply src/util/psbt/map/output.rs]: Fixed

File: src/util/psbt/map/output.rs (hunk 2 above)
Comment (dr-orlovsky) [reply src/util/psbt/map/output.rs:125]: Reworked that way.

File: src/util/taproot.rs [hunk 3]
```diff
@@ -451,6 +451,18 @@ impl TaprootBuilder {
         self.branch.len() == 1 && self.branch[0].is_some()
     }
 
+    /// Checks if the builder has hidden parts.
+    pub fn has_hidden(&self) -> bool {
```
Comment (sanket1729) [inline src/util/taproot.rs:455]: nit: 
`has_hidden_branches` or `has_hidden_leaves` instead? I am not a big fan of names where humans have to reason about things in order to complete them "has hidden what?", "Oh, must be `has_hidden_leaves`".

File: src/util/taproot.rs [hunk 4]
```diff
@@ -448,7 +448,7 @@ impl TaprootBuilder {
 
     /// Checks if the builder is a complete tree.
     pub fn is_complete(&self) -> bool {
-        self.branch.len() == 1 && self.branch[0].is_some()
+        self.branch.len() == 1 && self.branch[0].is_some() && !self.has_hidden()
```
Comment (sanket1729) [inline src/util/taproot.rs:451]: I don't think we should be updating this function here. Instead, we should be using it in psbt `TapTree::from_inner()` check. Trees can be complete and well-formed even if they contain hidden nodes.

File: src/util/psbt/serialize.rs [hunk 5]
```diff
@@ -370,8 +370,33 @@ fn key_source_len(key_source: &KeySource) -> usize {
 
 #[cfg(test)]
 mod tests {
+    use hashes::hex::FromHex;
     use super::*;
 
+    // Composes tree matching a given depth map, filled with dumb script leafs,
+    // each of which consists of a single push-int op code, with int value
+    // increased for each consecutive leaf.
+    pub fn compose_taproot_builder(opcode: u8, depth_map: impl IntoIterator<Item = u8>) -> TaprootBuilder {
```
Comment (sanket1729) [inline src/util/psbt/serialize.rs:379]: nit: Why `pub`?

File: src/util/psbt/map/output.rs (hunk 2 above)
Comment (sanket1729) [reply src/util/psbt/map/output.rs:125]: I will let him comment on this.

**Review by sanket1729 — COMMENTED** [review]
Some MSRV failures. I like this better, left a few comments that should be discussed

File: src/util/taproot.rs (hunk 3 above)
Comment (dr-orlovsky) [reply src/util/taproot.rs:455]: Originally I did it as `has_hidden_branches`. Than, I had a though, "may be this is leaves?". Than I have found that the only unambiguous guess present in current API is `add_hidden`, and decided to skip the suffix. No idea how "branch" is different from "node", "part" etc - we have no terminology in place yet in this area.

File: src/util/taproot.rs (hunk 4 above)
Comment (dr-orlovsky) [reply src/util/taproot.rs:451]: Also thought. But than, is the tree considered "complete" having hidden nodes? May be this method should be named "is_finalizable"?

File: src/util/psbt/serialize.rs (hunk 5 above)
Comment (dr-orlovsky) [reply src/util/psbt/serialize.rs:379]: Had plans to use it in `taproot` mod to do more extensive tests

File: src/util/psbt/map/output.rs (hunk 2 above)
Comment (dr-orlovsky) [reply src/util/psbt/map/output.rs:125]: Invoking @Kixunil: please see above.

File: src/util/taproot.rs (hunk 4 above)
Comment (sanket1729) [reply src/util/taproot.rs:451]: > But than, is the tree considered "complete" having hidden nodes?

I think there are two different things here. Builder is called `complete` if there is nothing else to add. In that sense using `complete` makes sense here. I don't mind renaming this to `is_finalizable`. 

`TapTree` is always complete.

File: src/util/psbt/map/output.rs (hunk 2 above)
Comment (sanket1729) [reply src/util/psbt/map/output.rs:125]: FWIW, I like the implemented solution in this PR in case we decide to proceed with this.

Comment (Kixunil) [reply src/util/psbt/map/output.rs:125]: Yes, error wrapper containing original data is even more idiomatic Rust. [`PoisonError`](https://doc.rust-lang.org/std/sync/struct.PoisonError.html) is a good example of this.

It could be interesting to do it the way `std` does - instead of private field have accessor methods, so that the type can be extended. Or add a dummy field to emulate `#[non_exhaustive]` (and change it to `#[non_exhaustive]` after MSRV bump). Not sure how likely the change is here (writing this in hurry).

**Comment by dr-orlovsky** [comment]
@sanket1729 addressed all your comments & rebased

**Review by sanket1729 — DISMISSED** [review]
c9fa3a9a77c7831ba6cedfaa39bf8a4985af85c7 also does not compile. 

I think you can squash or re-order "Prevent TapTree from hidden parts" and "TapTree hidden branches unit test".

**Comment by sanket1729** [comment]
I like the PR, will ACK after the commits pass tests.

**Comment by sanket1729** [comment]
If this release is getting delayed anyway, IMO we can do the clean solution with Hidden leaves instead. We don't need to restrict ourselves artificially with trees only containing full leaves.

File: src/util/taproot.rs [hunk 6]
```diff
@@ -461,11 +461,23 @@ impl TaprootBuilder {
...
+    /// Checks if the builder has hidden parts.
+    pub fn has_hidden(&self) -> bool {
+        for node in &self.branch {
+            if let Some(node) = node {
+                if node.has_hidden_leaves {
+                    return true
+                }
+            }
+        }
+        return false;
```
Comment (tcharding) [inline src/util/taproot.rs:478]:
```suggestion
        false
```

File: src/util/taproot.rs (hunk 3 above)
Comment (tcharding) [reply src/util/taproot.rs:470]: I'm out of my depth here but if 'parts' is correct in the rustdoc then wouldn't `has_hidden_parts` be a descriptive name?

Comment (dr-orlovsky) [reply src/util/taproot.rs:470]: "Hidden" can be a script leaf or a tree branch, thus we need some term to describe it. I see only two applicable terms here: `hidden_tips` and `hidden_parts`. But then we also have to rename `TreeBuilder::add_hidden`, and I am not happy with both `add_hidden_tip` and `add_hidden_part`. This also brings us to https://github.com/rust-bitcoin/rust-bitcoin/pull/924#issuecomment-1088232833 where `TipNode` can be used as an enum name for both script leafs and hidden (something).

**Comment by dr-orlovsky** [comment]
> If this release is getting delayed anyway, IMO we can do the clean solution with Hidden leaves instead. We don't need to restrict ourselves artificially with trees only containing full leaves.

@sanket1729 I did what I think the best solution for now in the latest version of #924 and provided rationale in https://github.com/rust-bitcoin/rust-bitcoin/pull/924#issuecomment-1088232833. Right now we do not have hidden branches to iterate over, so adding that second iterator in this release does not makes a lot of sense. Please let me know if you are ok with this approach.

Also pls let me know do I need to discard your review by fixing single non-compilling commit in the history, or it can go like that. @tcharding I will address your comments iff I will be force-pushing again.

**Comment by sanket1729** [comment]
@dr-orlovsky , you can force push

**Comment by sanket1729** [comment]
@dr-orlovsky if you can force push, I will be prompt to review today.

**Comment by dr-orlovsky** [comment]
Force-pushed fully reordering commits, checking each to be compiling & addressing all @sanket1729 and @tcharding comments. Also renamed `*_hidden` into `*_hidden_node`, since it is a tree node which is hidden (leaf is also a form of node).

File: src/util/taproot.rs (hunk 3 above)
Comment (dr-orlovsky) [reply src/util/taproot.rs]: Had come to conclusion that "hidden something" can always be called a "node". Updated all names accordingly.

**Review by sanket1729 — APPROVED** [review]
ACK 77715311cf0a68a3623f989393d4a58bc7e884ba . 

Reviwed the range diff. Why did you remove the test

```diff
 
-    #[test]
-    fn taptree_hidden() {
-        let mut builder = compose_taproot_builder(0x51, &[2, 2, 2]);
-        builder = builder.add_leaf_with_ver(3, Script::from_hex("b9").unwrap(), LeafVersion::from_consensus(0xC2).unwrap()).unwrap();
-        builder = builder.add_hidden(3, sha256::Hash::default()).unwrap();
-        assert!(TapTree::from_inner(builder.clone()).is_err());
-    }
-

```

**Comment by dr-orlovsky** [comment]
@sanket1729 s**, this happened during re-ordering of the commitments. Added it back - sorry will do it on top.

**Review by sanket1729 — APPROVED** [review]
ACK c036b0db6f199373e15b7cd0498ecca0ebd5af00. Reviewed the range diff

**Comment by tcharding** [comment]
Awesome thanks, all looks good to me.

File: src/util/taproot.rs (hunk 4 above)
Comment (apoelstra) [reply src/util/taproot.rs]: `is_finalizable` would be ok but this PR uses `is_finalized` which does not make sense to me

File: src/util/psbt/serialize.rs [hunk 7]
```diff
@@ -355,7 +355,7 @@ impl Deserialize for TapTree {
             builder = builder.add_leaf_with_ver(*depth, script, leaf_version)
                 .map_err(|_| encode::Error::ParseFailed("Tree not in DFS order"))?;
         }
-        if builder.is_finalized() {
+        if builder.is_finalized() || !builder.has_hidden_nodes() {
```
Comment (apoelstra) [inline src/util/psbt/serialize.rs:358]: In 77715311cf0a68a3623f989393d4a58bc7e884ba:

I don't understand the name `is_finalized` but I'm pretty sure this `||` is supposed to be a `&&`.

Comment (sanket1729) [reply src/util/psbt/serialize.rs:358]: This is a serious issue.
