### PR TITLE
Fix `no_std` when `bitcoinconsensus` is enabled

### LINKED ISSUE #1343: Resolve `bitcoinconsensus` mess-up
`bitcoinconsensus` has now `std` as a default feature and we don't import it with `default-features = false`. Thanks to this #1235 is not actually broken but we can't blindly put `default-features = false`. We have to make `bitcoinconsensus-std = ["bitcoinconsensus/std"]` feature and only return `Some` in the `source` if the feature is on. Fall back to printing the source otherwise.

### PR DESCRIPTION
**Pull request by Kixunil**
`default-features = false` was missing previously but blindly adding it would lead to subtle risk of breaking when a crate not needing `std` depends on `bitcoinconsensus` and simultaneously another crate not needing `bitcoinconsensus` depends on `std` and another crate depends on them both.

This change fixes it by introducing `bitcoinconsensus-std` feature flag and provides a fallback if the flag is off. Unfortunately the fallback has to use a bit of reasonable `unsafe` due to limitations of upcasting.

The only safe alternatives are not do it and provide worse experience for crates that are affected by the problem above or break the API, which couldn't be backported and would be more annoying to use.

Closes #1343

This is considered PoC PR as I realized the possibility of the hack (and necessity of `unsafe`) at the last moment. Things like tests and modifying CONTRIBUTING to change the stance on `unsafe` will be added if `unsafe` is ACKed.

### CODE REVIEW

File: bitcoin/src/blockdata/script.rs [hunk 1]
```diff
@@ -170,14 +170,54 @@ pub enum Error {
...
+
+    // bitcoinconsensus::Error has no sources at this time
+    impl std::error::Error for Error {}
+
+    pub(crate) fn wrap_error(error: &bitcoinconsensus::Error) -> &Error {
+        // Unfortunately, we cannot have the reference inside `Error` struct because of the 'static
+        // bound on `source` return type, so we have to use unsafe to overcome the limitation.
+        // SAFETY: the type is repr(transparent) and the lifetimes match
+        unsafe {
+            &*(error as *const _ as *const Error)
```
Comment (apoelstra) [inline bitcoin/src/blockdata/script.rs:202]: Could you do a `transmute<&'a bitcoinconsensus::Error, &'a Error>` so that it's clear that the lifetimes match and that you're just turning one kind of pointer into another?

**Comment by apoelstra** [comment]
Is the plan to push this hack out in a minor release, then in the next major release to remove it (maybe replace with some simpler hack)? This looks like it'll work but it's a lot of machinery for such an edge case.

File: bitcoin/src/blockdata/script.rs [hunk 2]
```diff
@@ -170,14 +170,54 @@ pub enum Error {
     Serialization
 }
 
+// If bitcoinonsensus-std is off but bitcoinconsensus is present we patch the error type to
+// implement `std::error::Error`.
+#[cfg(all(feature = "std", feature = "bitcoinconsensus", not(feature = "bitcoinconsensus-std")))]
```
Comment (tcharding) [inline bitcoin/src/blockdata/script.rs:175]: Why don't we just use
```
compile_error!("In order to use the features bitcoinconsensus and std please enable bitcoinconsensus-std as well");
```
So we fail to compile if users don't enable `bitcoinconsensus-std`. Then we can do away with all the error wrapping.

Comment (apoelstra) [reply bitcoin/src/blockdata/script.rs:175]: Because we may have one crate in a dep tree that uses `std`, and another one that uses `bitcoinconsensus` but not `std`, and no individual crate can be held responsible for enabling `bitcoinconsensus-std`.

Ultimately I feel like this problem is a cargo bug (or design flaw) rather than something we should have to deal with ... but it is what it is.

Comment (tcharding) [reply bitcoin/src/blockdata/script.rs:175]: I think I understand the problem, my idea is just instead of wrapping the error when the problem arises, fail to build so that the responsibility of enabling things correctly is forced onto `rust-bitcoin` (and yes I agree that enabling features in optional dependencies seems broken in general).

File: bitcoin/src/blockdata/script.rs (hunk 1 above)
Comment (Kixunil) [reply bitcoin/src/blockdata/script.rs:202]: AFAIK pointer casts are preferred to transmutes by Rust community but I will investigate.

File: bitcoin/src/blockdata/script.rs (hunk 2 above)
Comment (apoelstra) [reply bitcoin/src/blockdata/script.rs:175]: We really do not want to "fail to build" when we're included in certain shapes of dependency tree.

Comment (tcharding) [reply bitcoin/src/blockdata/script.rs:175]: Oh of course, that is the whole reason for starting this work - face palm

**Comment by Kixunil** [comment]
> Is the plan to push this hack out in a minor release, then in the next major release to remove it (maybe replace with some simpler hack)? 

I'm not sure. We need to address the edge case but AFAICT we have only these options:

* This hack
* Fall back to worse behavior: returning `None` from `source` and writing the source in the message instead - what we do for `no_std`. This could cause inconsistent displaying of errors - different separators used.
* Have custom `ConsensusError` type that is practically same as the internal `Error` type in this hack but is exposed in the API. This clutters the API a bit but allows us to remove `unsafe` completely. OTOH it also allows us to put more context into the error type in the future which could be useful.
* Raise MSRV to 1.65.0 and use cargo-native solution. I'd actually like to do this in ~2 years.

File: bitcoin/src/blockdata/script.rs (hunk 2 above)
Comment (Kixunil) [reply bitcoin/src/blockdata/script.rs:175]: > I feel like this problem is a cargo bug (or design flaw)

Yes, it is and it's fixed in 1.65 - yep, to be released soon.

>  fail to build so that the responsibility of enabling things correctly is forced onto `rust-bitcoin`

That will not force responsibility on `rust-bitcoin` but on whichever crate happened to include two dependencies which themselves include `rust-bitcoin`.

File: bitcoin/src/blockdata/script.rs (hunk 1 above)
Comment (apoelstra) [reply bitcoin/src/blockdata/script.rs:202]: A transmute would be safer because you can force transmutes not to change lifetimes.

Comment (Kixunil) [reply bitcoin/src/blockdata/script.rs:202]: The signature is already doing that, though.

Comment (apoelstra) [reply bitcoin/src/blockdata/script.rs:202]: Sure, but the signature is at the function level. The transmute controls the lifetime at the point of the transmute call. So if someone were to change the function signature for some reason to something that'd be unsafe, or if thte result of the transmute were used as an intermediate value in an illegal way, then the transmute would stop compiling.

**Comment by tcharding** [comment]
Can I ask a question, if I'm understanding this correctly, here we are providing a solution to a issue in `cargo` that will arise only if someone publishes a crate that is a no-std only crate that depends on `rust-bitcoin` _with_ the "bitcoinconsensus" feature enabled and someone wants to use that crate at the same time as using another crate that enables rust-bitcoin using the "std" feature. This seems like one hell of an edge case?

Instead of this workaround wouldn't it be better if the hypothetical no-std only crate added a "std" feature? I'm not well versed on the exact situation but it seems that "no-std" is not fully working in the rust ecosystem, anyone doing embedded dev is going to be well aware of all these problems. Since adding "std" support is trivial (add `source` implementation for all errors) I can't see anyone not doing this, or am I wrong? Am I missing something?

**Comment by Kixunil** [comment]
Yes.

> This seems like one hell of an edge case?

And it is *our* responsibility to handle it.

> Instead of this workaround wouldn't it be better if the hypothetical no-std only crate added a "std" feature?

This still wouldn't help, since a downstream crate could just not enable it.

>  anyone doing embedded dev is going to be well aware of all these problems.

Ironically, this doesn't affect embedded users but `std` users.

If you don't like this workaround there's a less nice non-`unsafe` alternative with a bit less code: just write the error source inline if the edge case is hit like we do for `no_std`. I personally prefer giving consumers better experience but if people want to sacrifice it for the lack of `unsafe` I'm willing to rewrite it.

**Comment by tcharding** [comment]
> And it is our responsibility to handle it.

I'm still not convinced this is our problem to fix, imagine
- crate a depends on `rust-bitcoin` with "no-std,bitcoinconsensus" features
- crate b depends on `rust-bitcoin` with "std"
- crate c depends on crate a and crate b - build breaks (assuming we add no-deafult-features to our bitcoinconsensus dependency)

Who's fault is this build fail? Its clearly not the fault of crate a or crate b. Is it crate c's fault for misscombining crate a and crate b?  This PR argues that its the fault of `rust-bitcoin` but I'd argue that its not the fault of rust-bitcoin but the fault of `cargo`. The solution in this PR implies that every crate in the rust ecosystem is to implement this sort of hack - that is not an acceptable fix in my opinion. My suggestion would be either to fix it in cargo (which I'm not going to do) and short of that just document it at the source of the build fail, since the compiler is going to point to that line and devs can jump there and see the docs immediately.

E.g.,
```rust
            // If your build is breaking with:
            //
            // "the trait `std::error::Error` is not implemented for `bitcoinconsensus::Error`"
            //
            // you should add a dependency on rust-bitcoinconsensus with the "std" feature enabled.
            // The reason is that some crate you depend on is depending on bitcoinconsensus with
            // "std" not enabled (could be via depending on rust-bitcoin with "bitcoinconsensus" and
            // "no-std") and there is no other way to enable features in a dependency of a dependency.
            #[cfg(feature = "bitcoinconsensus")]
            BitcoinConsensus(ref e) => Some(e),
```

**Comment by tcharding** [comment]
If we do merge this PR we would then have to do another one the same for every other optional dependency we have (assuming we use an error type from it).

**Comment by tcharding** [comment]
FTR I've tested this PR  and it definitely does work.

**Comment by Kixunil** [comment]
> Is it crate c's fault for misscombining crate a and crate b?

If it was so easy that just by miscombining crates you get build failure I'd agree making it straight up readable `compile_error!`. However if in your example crate `a` didn't depend on `bitcoinconsensus` and started depending later it'd be a breaking change.

We could document that activating any features may break downstream crates but I don't believe it's practical. It is **very** likely people will miss it or forget it because it never happens in normal crates.

> the fault of `cargo`

As I already said this is fixed in 1.65.0. Do you think anyone here will agree to raise MSRV to 1.65? But sure in two years, I will be happy to send a PR that does the actual right thing.

> If we do merge this PR we would then have to do another one the same for every other optional dependency we have

Yes and I believe it's the right thing to do.

> assuming we use an error type from it

Not just error type, anything conditionally-compiled that depends on a feature of upstream crate. Error types are just the most common and obvious examples.

**Review by tcharding — APPROVED** [review]
tACK b6f9e47dba9b784c9a51cec2d182ea913088e724

**Review by apoelstra — APPROVED** [review]
ACK b6f9e47dba9b784c9a51cec2d182ea913088e724
